//! Default configuration constants.
//!
//! Contains the default TOML config content and provider TOML templates
//! generated by `llm-proxy init`.

/// Default main config TOML content generated by `llm-proxy init`.
///
/// Contains server settings only. Provider routing is configured in
/// individual provider TOML files under `providers/`. Does NOT include:
/// - sampling overrides (temperature, top_p, etc.)
/// - tool overrides
/// - reasoning/thinking overrides
/// - cache settings
/// - stream overrides
/// - fallback/scenario logic
pub const DEFAULT_CONFIG_TOML: &str = r#"[server]
bind = "127.0.0.1:3456"
request_timeout = "300s"
log_level = "info"
hot_reload = false
rate_limit_rpm = 100
trust_forwarded_headers = false
dedup_window = "0ms"
server_name = "llm-proxy"
"#;

/// Default provider TOML for opencode-go.
///
/// Uses provider-based routing: inbound route kinds (chat completions,
/// messages) are mapped to adapters in `[provider.routes]`.
pub const DEFAULT_PROVIDER_OPENCODE_GO: &str = r#"[provider]
name = "opencode-go"
api_key = "${LLM_PROXY_OPENCODE_GO_KEY}"
auth_style = "bearer"

[provider.adapters.chat]
protocol = "openai_chat_completions"
endpoint = "https://opencode.ai/zen/go/v1/chat/completions"

[provider.adapters.anthropic]
protocol = "anthropic_messages"
endpoint = "https://opencode.ai/zen/go/v1/messages"

[provider.routes]
chat_completions = "chat"
messages = "anthropic"

# [provider.model_aliases]
# "alias" = "upstream-model-id"

# [provider.discovery]
# kind = "openai_compatible_models"
# endpoint = "https://opencode.ai/zen/go/v1/models"
# max_pages = 100
# max_models = 20000
# max_response_bytes = 4194304
"#;

/// Default provider TOML for opencode-zen.
///
/// Uses provider-based routing: inbound route kinds (chat completions,
/// messages) are mapped to adapters in `[provider.routes]`.
pub const DEFAULT_PROVIDER_OPENCODE_ZEN: &str = r#"[provider]
name = "opencode-zen"
api_key = "${LLM_PROXY_OPENCODE_ZEN_KEY}"
auth_style = "bearer"

[provider.adapters.chat]
protocol = "openai_chat_completions"
endpoint = "https://opencode.ai/zen/v1/chat/completions"

[provider.adapters.anthropic]
protocol = "anthropic_messages"
endpoint = "https://opencode.ai/zen/v1/messages"

[provider.adapters.responses]
protocol = "openai_responses"
endpoint = "https://opencode.ai/zen/v1/responses"

[provider.adapters.gemini]
protocol = "gemini_generate_content"
endpoint = "https://opencode.ai/zen/v1/models/{model}:generateContent"

[provider.routes]
chat_completions = "chat"
messages = "anthropic"

# [provider.model_aliases]
# "alias" = "upstream-model-id"

# [provider.discovery]
# kind = "openai_compatible_models"
# endpoint = "https://opencode.ai/zen/v1/models"
# max_pages = 100
# max_models = 20000
# max_response_bytes = 4194304
"#;
