//! `llm-proxy` binary -- CLI entry point.
//!
//! Multi-command CLI for the LLM proxy server. Uses TOML config exclusively;
//! legacy JSON config is rejected with a migration error directing users to
//! `llm-proxy init`.
//!
//! Commands:
//!
//! - `serve`    Start the proxy server (foreground or daemon)
//! - `stop`     Stop a running daemon
//! - `status`   Check if the server is running
//! - `init`     Create default TOML config and provider files
//! - `validate` Validate TOML config and print provider route table
//! - `models`   List provider-scoped models
//! - `autostart` Manage auto-start on login (enable / disable / status)

use std::io::Write;
use std::path::PathBuf;

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};
use llm_proxy_core::{AppConfig, ProviderRegistry, load_app_config};
use llm_proxy_provider::{ProviderAdapterRegistry, ProxyClient};
use llm_proxy_server::{AppState, BuildInfo, build_router, shutdown_signal};
use tokio::net::TcpListener;
use tracing::info;

// ---------------------------------------------------------------------------
// CLI definitions
// ---------------------------------------------------------------------------

/// LLM proxy server.
#[derive(Parser, Debug)]
#[command(
    name = "llm-proxy",
    version,
    about = "LLM proxy server with provider-based model routing",
    propagate_version = true
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Start the proxy server.
    Serve {
        /// Path to config file (must be TOML).
        #[arg(short, long)]
        config: Option<PathBuf>,
        /// Override listen port.
        #[arg(short, long)]
        port: Option<u16>,
        /// Run as background daemon.
        #[arg(short, long)]
        background: bool,
        /// Internal: used by daemon child process.
        #[arg(long, hide = true)]
        daemonize: bool,
    },
    /// Stop a running server.
    Stop,
    /// Check if the server is running.
    Status,
    /// Create a default config file.
    Init,
    /// Validate a config file and print settings.
    Validate {
        /// Path to config file (must be TOML).
        #[arg(short, long)]
        config: Option<PathBuf>,
    },
    /// List provider-scoped models.
    Models {
        /// Path to config file (must be TOML).
        #[arg(short, long)]
        config: Option<PathBuf>,
    },
    /// Manage auto-start on login.
    Autostart {
        #[command(subcommand)]
        action: AutostartAction,
    },
}

#[derive(Subcommand, Debug)]
enum AutostartAction {
    /// Enable auto-start.
    Enable {
        /// Path to config file.
        #[arg(short, long)]
        config: Option<PathBuf>,
        /// Port to listen on.
        #[arg(short, long)]
        port: Option<u16>,
    },
    /// Disable auto-start.
    Disable,
    /// Show auto-start status.
    Status,
}

// ---------------------------------------------------------------------------
// Migration error message
// ---------------------------------------------------------------------------

/// Migration error printed when legacy JSON config is detected.
const MIGRATION_ERROR: &str = "\
JSON oc-go-cc config is no longer supported by serve.\n\
Run `llm-proxy init` to create TOML config, then copy model/API settings.";

// ---------------------------------------------------------------------------
// Default TOML config content
// ---------------------------------------------------------------------------

/// Default main config TOML content generated by `llm-proxy init`.
///
/// Contains server settings only. Provider routing is configured in
/// individual provider TOML files under `providers/`. Does NOT include:
/// - sampling overrides (temperature, top_p, etc.)
/// - tool overrides
/// - reasoning/thinking overrides
/// - cache settings
/// - stream overrides
/// - fallback/scenario logic
const DEFAULT_CONFIG_TOML: &str = r#"[server]
bind = "127.0.0.1:3456"
request_timeout = "300s"
log_level = "info"
hot_reload = false
server_name = "llm-proxy"
"#;

/// Default provider TOML for opencode-go.
///
/// Uses provider-based routing: adapters are matched by protocol to
/// route kinds (chat completions, messages, etc.). Model-to-adapter
/// mappings are in `[provider.models]`.
const DEFAULT_PROVIDER_OPENCODE_GO: &str = r#"[provider]
name = "opencode-go"
api_key = "${LLM_PROXY_OPENCODE_GO_KEY}"
auth_style = "bearer"

[provider.adapters.chat]
protocol = "openai_chat_completions"
endpoint = "https://opencode.ai/zen/go/v1/chat/completions"

[provider.adapters.anthropic]
protocol = "anthropic_messages"
endpoint = "https://opencode.ai/zen/go/v1/messages"

[provider.models]
"kimi-k2.6" = { adapter = "chat" }
"glm-5" = { adapter = "chat" }
"glm-5.1" = { adapter = "chat" }
"qwen3.5-plus" = { adapter = "chat" }
"deepseek-v4-pro" = { adapter = "chat" }
"minimax-m2.5" = { adapter = "chat" }
"#;

/// Default provider TOML for opencode-zen.
///
/// Uses provider-based routing: adapters are matched by protocol to
/// route kinds (chat completions, messages, etc.). Model-to-adapter
/// mappings are in `[provider.models]`.
const DEFAULT_PROVIDER_OPENCODE_ZEN: &str = r#"[provider]
name = "opencode-zen"
api_key = "${LLM_PROXY_OPENCODE_ZEN_KEY}"
auth_style = "bearer"

[provider.adapters.chat]
protocol = "openai_chat_completions"
endpoint = "https://opencode.ai/zen/v1/chat/completions"

[provider.adapters.anthropic]
protocol = "anthropic_messages"
endpoint = "https://opencode.ai/zen/v1/messages"

[provider.adapters.responses]
protocol = "openai_responses"
endpoint = "https://opencode.ai/zen/v1/responses"

[provider.adapters.gemini]
protocol = "gemini_generate_content"
endpoint = "https://opencode.ai/zen/v1/models/{model}:generateContent"

[provider.models]
"gpt-5.4" = { adapter = "chat" }
"gpt-5.4-pro" = { adapter = "chat" }
"gemini-3.5-flash" = { adapter = "gemini" }
"claude-sonnet-4-20250514" = { adapter = "anthropic" }
"#;

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

/// Config directory: `~/.config/llm-proxy/`.
///
/// Falls back to `./.config/llm-proxy/` (relative to current working directory)
/// when `$HOME` and `$USERPROFILE` are both unset. This is unlikely in practice
/// but avoids a panic.
fn config_dir() -> PathBuf {
    home_env::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".config")
        .join("llm-proxy")
}

/// Config file path: `~/.config/llm-proxy/config.toml`.
fn default_config_path() -> PathBuf {
    config_dir().join("config.toml")
}

/// PID file path: `~/.config/llm-proxy/llm-proxy.pid`.
fn pid_file_path() -> PathBuf {
    config_dir().join("llm-proxy.pid")
}

/// Resolve the config file path for `serve`.
///
/// Priority:
/// 1. Explicit CLI `--config` argument
/// 2. `$LLM_PROXY_CONFIG` env var (preferred)
/// 3. `$OC_GO_CC_CONFIG` env var (legacy, triggers migration warning)
/// 4. Default path `~/.config/llm-proxy/config.toml`
///
/// Returns `(resolved_path, legacy_env_detected)`.
/// `legacy_env_detected` is true when `$OC_GO_CC_CONFIG` was the source
/// and neither CLI nor `$LLM_PROXY_CONFIG` was provided.
fn resolve_serve_config(cli_path: Option<&std::path::Path>) -> (PathBuf, bool) {
    // 1. Explicit CLI path always wins.
    if let Some(p) = cli_path {
        return (p.to_path_buf(), false);
    }
    // 2. Preferred env var.
    if let Ok(p) = std::env::var("LLM_PROXY_CONFIG") {
        if !p.is_empty() {
            return (PathBuf::from(p), false);
        }
    }
    // 3. Legacy env var (detected for migration warning).
    if let Ok(p) = std::env::var("OC_GO_CC_CONFIG") {
        if !p.is_empty() {
            return (PathBuf::from(p), true);
        }
    }
    // 4. Default.
    (default_config_path(), false)
}

/// Resolve the config file path for non-serve commands (validate, models).
///
/// Priority:
/// 1. Explicit CLI `--config` argument
/// 2. `$LLM_PROXY_CONFIG` env var
/// 3. Default path
fn resolve_config(cli_path: Option<&std::path::Path>) -> PathBuf {
    if let Some(p) = cli_path {
        return p.to_path_buf();
    }
    if let Ok(p) = std::env::var("LLM_PROXY_CONFIG") {
        if !p.is_empty() {
            return PathBuf::from(p);
        }
    }
    default_config_path()
}

/// Returns the providers directory path, which is always `providers/`
/// next to the config file.
///
/// Falls back to `./providers` if the config path has no parent directory
/// (e.g. bare filename `config.toml` with no directory component).
fn providers_dir_for(config_path: &std::path::Path) -> PathBuf {
    config_path
        .parent()
        .unwrap_or(std::path::Path::new("."))
        .join("providers")
}

/// Returns the launchd plist path on macOS.
///
/// Falls back to `./com.llm-proxy.plist` if home directory cannot be determined.
#[cfg(target_os = "macos")]
fn launchd_plist_path() -> PathBuf {
    home_env::home_dir()
        .map(|h| {
            h.join("Library")
                .join("LaunchAgents")
                .join("com.llm-proxy.plist")
        })
        .unwrap_or_else(|| PathBuf::from("com.llm-proxy.plist"))
}

/// Returns the XDG autostart directory on Linux.
///
/// Falls back to `./.config/autostart` if home directory cannot be determined.
#[cfg(target_os = "linux")]
fn linux_autostart_dir() -> PathBuf {
    home_env::home_dir()
        .map(|h| h.join(".config").join("autostart"))
        .unwrap_or_else(|| PathBuf::from(".config/autostart"))
}

// ---------------------------------------------------------------------------
// PID file helpers
// ---------------------------------------------------------------------------

/// Read the PID from the PID file. Returns `None` if the file does not exist.
fn read_pid() -> Result<Option<u32>> {
    let path = pid_file_path();
    if !path.exists() {
        return Ok(None);
    }
    let content = std::fs::read_to_string(&path)
        .with_context(|| format!("reading PID file {}", path.display()))?;
    let pid: u32 = content
        .trim()
        .parse()
        .with_context(|| format!("parsing PID from {}", path.display()))?;
    Ok(Some(pid))
}

/// Write the current PID to the PID file.
fn write_pid() -> Result<()> {
    let dir = config_dir();
    std::fs::create_dir_all(&dir)
        .with_context(|| format!("creating directory {}", dir.display()))?;
    let path = pid_file_path();
    let pid = std::process::id();
    let mut f = std::fs::File::create(&path)
        .with_context(|| format!("creating PID file {}", path.display()))?;
    write!(f, "{pid}").with_context(|| format!("writing PID file {}", path.display()))?;
    info!(pid, "wrote PID file");
    Ok(())
}

/// Remove the PID file.
fn remove_pid() -> Result<()> {
    let path = pid_file_path();
    if path.exists() {
        std::fs::remove_file(&path)
            .with_context(|| format!("removing PID file {}", path.display()))?;
    }
    Ok(())
}

/// Check if a process with the given PID is running.
///
/// On Unix, uses `kill(pid, 0)` which checks process existence without
/// sending a signal. Returns `true` when `kill` returns 0 (process exists
/// and we have permission) OR when it returns -1 with `EPERM` (process
/// exists but we lack permission to signal it). Only returns `false` when
/// `ESRCH` is returned (no such process).
fn is_process_running(pid: u32) -> bool {
    // SAFETY: kill(pid, 0) just checks if the process exists; it does not
    // send a signal on any Unix platform. The pid is validated to be a
    // non-zero positive integer by the caller (read from PID file).
    #[cfg(unix)]
    {
        let ret = unsafe { libc::kill(pid as i32, 0) };
        if ret == 0 {
            return true;
        }
        // EPERM means the process exists but we cannot signal it.
        #[cfg(target_os = "macos")]
        let errno = unsafe { *libc::__error() };
        #[cfg(target_os = "linux")]
        let errno = unsafe { *libc::__errno_location() };
        #[cfg(not(any(target_os = "macos", target_os = "linux")))]
        let errno: i32 = 0; // Assume not EPERM on other Unix platforms.
        errno == libc::EPERM
    }
    #[cfg(not(unix))]
    {
        // Fallback: always assume running on non-Unix.
        let _ = pid;
        true
    }
}

// ---------------------------------------------------------------------------
// Config extension validation
// ---------------------------------------------------------------------------

/// Check if a path points to a JSON config file.
fn is_json_config(path: &std::path::Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| e.eq_ignore_ascii_case("json"))
}

/// Check if a path points to a TOML config file.
fn is_toml_config(path: &std::path::Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| e.eq_ignore_ascii_case("toml"))
}

/// Validate that the config file path has a supported extension.
///
/// Rejects JSON paths with the migration error and non-TOML paths with an
/// unsupported-extension error. Returns `Ok(())` for `.toml` paths.
fn validate_toml_extension(path: &std::path::Path) -> Result<()> {
    if is_json_config(path) {
        bail!("{}", MIGRATION_ERROR);
    }
    if !is_toml_config(path) {
        bail!(
            "unsupported config file extension: {:?} (expected .toml)",
            path.extension()
                .map(|e| e.to_string_lossy())
                .unwrap_or_else(|| std::borrow::Cow::Borrowed("(none)"))
        );
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Serve {
            config,
            port,
            background,
            daemonize,
        } => cmd_serve(config, port, background, daemonize).await,
        Commands::Stop => cmd_stop(),
        Commands::Status => cmd_status(),
        Commands::Init => cmd_init(),
        Commands::Validate { config } => cmd_validate(config),
        Commands::Models { config } => cmd_models(config),
        Commands::Autostart { action } => match action {
            AutostartAction::Enable { config, port } => cmd_autostart_enable(config, port),
            AutostartAction::Disable => cmd_autostart_disable(),
            AutostartAction::Status => cmd_autostart_status(),
        },
    }
}

// ---------------------------------------------------------------------------
// Command implementations
// ---------------------------------------------------------------------------

/// Run the `serve` command.
///
/// Requires TOML config. JSON config is rejected with a migration error.
/// `$OC_GO_CC_CONFIG` alone emits the migration error. An explicit TOML
/// `--config` or `$LLM_PROXY_CONFIG` wins over `$OC_GO_CC_CONFIG`.
async fn cmd_serve(
    config_path: Option<PathBuf>,
    port_override: Option<u16>,
    background: bool,
    daemonize: bool,
) -> Result<()> {
    // If background mode requested, spawn self as child with --daemonize.
    if background && !daemonize {
        return spawn_daemon(config_path, port_override);
    }

    init_tracing();

    // Resolve config file path.
    let (path, legacy_env) = resolve_serve_config(config_path.as_deref());

    // Reject JSON config and non-TOML extensions with migration/unsupported error.
    validate_toml_extension(&path)?;

    // If only $OC_GO_CC_CONFIG is set (no explicit --config, no $LLM_PROXY_CONFIG),
    // print migration error and exit. This rejects $OC_GO_CC_CONFIG regardless of
    // file extension: even TOML files via this env var are rejected to force users
    // to migrate to the preferred $LLM_PROXY_CONFIG or explicit --config.
    if legacy_env {
        bail!("{}", MIGRATION_ERROR);
    }

    // Build shared infrastructure.
    let adapter_registry = ProviderAdapterRegistry::builtin();
    let proxy_client = ProxyClient::new();

    // Check if already running.
    if let Some(pid) = read_pid()? {
        if is_process_running(pid) {
            bail!(
                "server already running with PID {} (PID file: {})",
                pid,
                pid_file_path().display()
            );
        }
        info!("stale PID file found, cleaning up");
        remove_pid()?;
    }

    // Write PID file.
    write_pid()?;

    // Ensure PID file is cleaned up on shutdown.
    let pid_path = pid_file_path();
    let cleanup = async move {
        if let Err(e) = std::fs::remove_file(&pid_path) {
            tracing::warn!(error = %e, "failed to remove PID file during shutdown");
        }
    };

    // Load TOML config and build state (consumes adapter_registry and proxy_client).
    let state = load_toml_state(&path, adapter_registry, proxy_client, port_override)?;

    let bind_addr = state.bind_address();
    let app = build_router(state);

    let listener = TcpListener::bind(bind_addr)
        .await
        .with_context(|| format!("binding to {bind_addr}"))?;
    info!(
        addr = %listener.local_addr()?,
        version = env!("CARGO_PKG_VERSION"),
        "llm-proxy listening"
    );

    // Serve with graceful shutdown.
    let result = axum::serve(listener, app)
        .with_graceful_shutdown(shutdown_signal())
        .await;

    cleanup.await;

    match result {
        Ok(()) => {
            info!("server stopped cleanly");
            Ok(())
        }
        Err(e) => {
            tracing::error!(error = %e, "server error");
            Err(anyhow::anyhow!("server error: {}", e))
        }
    }
}

/// Spawn the current binary as a background daemon.
fn spawn_daemon(config_path: Option<PathBuf>, port_override: Option<u16>) -> Result<()> {
    let exe = std::env::current_exe().with_context(|| "resolving current executable")?;
    let mut cmd = std::process::Command::new(&exe);
    cmd.arg("serve").arg("--daemonize");

    if let Some(ref p) = config_path {
        cmd.arg("--config").arg(p);
    }
    if let Some(p) = port_override {
        cmd.arg("--port").arg(p.to_string());
    }

    // Detach from terminal.
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        cmd.process_group(0);
        // Redirect stdout/stderr to a log file.
        let log_path = config_dir().join("llm-proxy.log");
        let log_file = std::fs::File::options()
            .create(true)
            .append(true)
            .open(&log_path)
            .with_context(|| format!("opening log file {}", log_path.display()))?;
        cmd.stdout(
            log_file
                .try_clone()
                .with_context(|| "cloning log file handle")?,
        );
        cmd.stderr(log_file);
    }

    #[cfg(not(unix))]
    {
        println!(
            "warning: daemon log redirection is not supported on this platform; \
                   output will be lost"
        );
    }

    let mut child = cmd.spawn().with_context(|| "spawning daemon process")?;

    let pid = child.id();
    println!("llm-proxy started in background (PID {pid})");
    println!("  config dir: {}", config_dir().display());
    println!(
        "  log file:   {}",
        config_dir().join("llm-proxy.log").display()
    );

    // Detach from child so we don't wait on it.
    if let Err(e) = child.try_wait() {
        tracing::warn!(error = %e, "failed to check daemon child status");
    }

    Ok(())
}

/// Run the `stop` command.
fn cmd_stop() -> Result<()> {
    match read_pid()? {
        Some(pid) => {
            if !is_process_running(pid) {
                println!("server not running (stale PID {pid})");
                remove_pid()?;
                return Ok(());
            }

            #[cfg(unix)]
            {
                // Send SIGTERM.
                let ret = unsafe { libc::kill(pid as i32, libc::SIGTERM) };
                if ret != 0 {
                    bail!("failed to send SIGTERM to PID {pid}");
                }
            }

            println!("sent SIGTERM to PID {pid}");

            // Wait briefly for process to exit.
            for _ in 0..10 {
                if !is_process_running(pid) {
                    remove_pid()?;
                    println!("server stopped");
                    return Ok(());
                }
                std::thread::sleep(std::time::Duration::from_millis(200));
            }

            // Force kill if still running.
            #[cfg(unix)]
            {
                let ret = unsafe { libc::kill(pid as i32, libc::SIGKILL) };
                if ret != 0 {
                    bail!("failed to send SIGKILL to PID {pid}");
                }
            }
            remove_pid()?;
            println!("server force-stopped (PID {pid})");
            Ok(())
        }
        None => {
            println!("no PID file found -- server not running");
            Ok(())
        }
    }
}

/// Run the `status` command.
fn cmd_status() -> Result<()> {
    match read_pid()? {
        Some(pid) => {
            if is_process_running(pid) {
                println!("server is running (PID {pid})");
                // Try to load actual bind address from config.
                let config_path = default_config_path();
                if config_path.exists() {
                    if let Ok(cfg) = load_app_config(&config_path) {
                        println!("  listen: {}", cfg.server.bind);
                    } else {
                        println!("  listen: (could not parse config)");
                    }
                } else {
                    println!("  listen: (config not found: {})", config_path.display());
                }
                println!("  config: {}", config_path.display());
            } else {
                println!("server not running (stale PID {pid})");
            }
            Ok(())
        }
        None => {
            println!("server not running (no PID file)");
            Ok(())
        }
    }
}

/// Run the `init` command.
///
/// Creates:
/// - `config.toml` in the config directory
/// - `providers/opencode-go.toml` next to the config
/// - `providers/opencode-zen.toml` next to the config
///
/// Does NOT write:
/// - fallback/scenario JSON
/// - sampling/tool/reasoning/cache/stream overrides
fn cmd_init() -> Result<()> {
    let config_path = default_config_path();
    if config_path.exists() {
        bail!("config file already exists at {}", config_path.display());
    }

    let dir = config_dir();
    std::fs::create_dir_all(&dir)
        .with_context(|| format!("creating directory {}", dir.display()))?;

    // Write main config.toml with restrictive permissions (contains env var references).
    let mut f = std::fs::File::create(&config_path)
        .with_context(|| format!("creating {}", config_path.display()))?;
    f.write_all(DEFAULT_CONFIG_TOML.as_bytes())
        .with_context(|| format!("writing {}", config_path.display()))?;
    set_private_permissions(&config_path)?;
    println!("created config at {}", config_path.display());

    // Create providers directory.
    let providers_dir = providers_dir_for(&config_path);
    std::fs::create_dir_all(&providers_dir)
        .with_context(|| format!("creating directory {}", providers_dir.display()))?;

    // Write opencode-go provider with restrictive permissions.
    let go_path = providers_dir.join("opencode-go.toml");
    let mut f = std::fs::File::create(&go_path)
        .with_context(|| format!("creating {}", go_path.display()))?;
    f.write_all(DEFAULT_PROVIDER_OPENCODE_GO.as_bytes())
        .with_context(|| format!("writing {}", go_path.display()))?;
    set_private_permissions(&go_path)?;
    println!("created provider config at {}", go_path.display());

    // Write opencode-zen provider with restrictive permissions.
    let zen_path = providers_dir.join("opencode-zen.toml");
    let mut f = std::fs::File::create(&zen_path)
        .with_context(|| format!("creating {}", zen_path.display()))?;
    f.write_all(DEFAULT_PROVIDER_OPENCODE_ZEN.as_bytes())
        .with_context(|| format!("writing {}", zen_path.display()))?;
    set_private_permissions(&zen_path)?;
    println!("created provider config at {}", zen_path.display());

    println!();
    println!("Next steps:");
    println!("  1. Set API keys via environment variables:");
    println!("     export LLM_PROXY_OPENCODE_GO_KEY=your-go-key");
    println!("     export LLM_PROXY_OPENCODE_ZEN_KEY=your-zen-key");
    println!("  2. Run `llm-proxy validate` to check your config");
    println!("  3. Run `llm-proxy serve` to start the proxy");

    Ok(())
}

/// Run the `validate` command.
///
/// Loads main TOML, loads provider files, validates provider adapter protocols
/// against builtins, and prints provider route table.
fn cmd_validate(config_path: Option<PathBuf>) -> Result<()> {
    let path = resolve_config(config_path.as_deref());

    // Reject JSON config and non-TOML extensions.
    validate_toml_extension(&path)?;

    println!("validating config: {}", path.display());

    let app_config: AppConfig = load_app_config(&path)
        .with_context(|| format!("loading TOML config from {}", path.display()))?;

    // Print settings summary.
    println!();
    println!("=== Server Configuration ===");
    println!("  bind:            {}", app_config.server.bind);
    println!(
        "  request_timeout: {}s",
        app_config.server.request_timeout.as_secs()
    );
    println!("  log_level:       {}", app_config.server.log_level);
    println!("  hot_reload:      {}", app_config.server.hot_reload);
    println!("  server_name:     {}", app_config.server.server_name);

    // Load and validate providers.
    let providers_dir = providers_dir_for(&path);
    let registry = if providers_dir.exists() {
        ProviderRegistry::load_from_dir(&providers_dir)
            .with_context(|| format!("loading providers from {}", providers_dir.display()))?
    } else {
        ProviderRegistry::from_providers(vec![])
            .with_context(|| "building empty provider registry")?
    };

    // Validate provider protocols against builtin adapters.
    let adapter_registry = ProviderAdapterRegistry::builtin();
    let known_protocols = adapter_registry.protocol_names();
    registry
        .validate_protocols(known_protocols)
        .with_context(|| "validating provider protocols")?;

    println!();
    println!("=== Providers ({} loaded) ===", registry.len());
    if registry.is_empty() {
        println!("  (none)");
    } else {
        for provider in registry.iter() {
            println!(
                "  {} ({} adapters, {} models)",
                provider.name,
                provider.adapters.len(),
                provider.models.len()
            );
        }
    }

    // Print provider route table: provider -> model -> adapter/protocol
    println!();
    println!("=== Provider Routes ===");
    if registry.is_empty() {
        println!("  (no providers loaded)");
    } else {
        let mut route_errors: Vec<String> = Vec::new();
        for provider in registry.iter() {
            println!("{}:", provider.name);
            if provider.models.is_empty() {
                println!("  (no models configured)");
            } else {
                for (model_name, model_cfg) in &provider.models {
                    match provider.adapters.get(&model_cfg.adapter) {
                        Some(adapter) => {
                            println!(
                                "  {} -> {}/{}",
                                model_name, model_cfg.adapter, adapter.protocol
                            );
                        }
                        None => {
                            let msg = format!(
                                "  {} -> ERROR: unknown adapter \"{}\"",
                                model_name, model_cfg.adapter
                            );
                            println!("{}", msg);
                            route_errors.push(msg);
                        }
                    }
                }
            }
        }

        if !route_errors.is_empty() {
            bail!(
                "config has {} route resolution error(s)",
                route_errors.len()
            );
        }
    }

    println!();
    println!("Config is valid!");
    Ok(())
}

/// Run the `models` command.
///
/// Lists provider-scoped models from provider config files. Each provider's
/// model-to-adapter mappings are displayed grouped by provider name.
fn cmd_models(config_path: Option<PathBuf>) -> Result<()> {
    let path = resolve_config(config_path.as_deref());

    // Reject JSON config and non-TOML extensions.
    validate_toml_extension(&path)?;

    // Load providers from the providers/ directory next to the config.
    let providers_dir = providers_dir_for(&path);
    let registry = if providers_dir.exists() {
        ProviderRegistry::load_from_dir(&providers_dir)
            .with_context(|| format!("loading providers from {}", providers_dir.display()))?
    } else {
        ProviderRegistry::from_providers(vec![])
            .with_context(|| "building empty provider registry")?
    };

    if registry.is_empty() {
        println!("No providers configured.");
        println!("Add provider files to {}", providers_dir.display());
        return Ok(());
    }

    println!("Provider-scoped models (from {}):", providers_dir.display());
    println!();
    for provider in registry.iter() {
        if provider.models.is_empty() {
            println!("  {}:", provider.name);
            println!("    (no models configured, all models sent as-is to upstream)");
        } else {
            println!("  {}:", provider.name);
            for (model_name, model_cfg) in &provider.models {
                println!("    {} -> {}", model_name, model_cfg.adapter);
            }
        }
    }

    Ok(())
}

/// Run the `autostart enable` command.
fn cmd_autostart_enable(config_path: Option<PathBuf>, port: Option<u16>) -> Result<()> {
    let dir = config_dir();
    std::fs::create_dir_all(&dir)
        .with_context(|| format!("creating directory {}", dir.display()))?;

    let exe = std::env::current_exe().with_context(|| "resolving current executable")?;
    // Build args as strings for plist/desktop entry display. Lossy conversion is
    // acceptable here because these are display-only strings that are XML-escaped
    // by format_plist(). Non-UTF-8 paths are rare and the lossy replacement is
    // sufficient for auto-start purposes.
    let mut args = vec![exe.to_string_lossy().to_string(), "serve".to_string()];

    if let Some(ref p) = config_path {
        args.push("--config".to_string());
        args.push(p.to_string_lossy().to_string());
    }
    if let Some(p) = port {
        args.push("--port".to_string());
        args.push(p.to_string());
    }

    #[cfg(target_os = "macos")]
    {
        let plist_content = format_plist(&args.join(" "));
        let plist_path = launchd_plist_path();

        let plist_dir = plist_path
            .parent()
            .with_context(|| format!("invalid plist path: {}", plist_path.display()))?;
        std::fs::create_dir_all(plist_dir)
            .with_context(|| format!("creating {}", plist_dir.display()))?;

        std::fs::write(&plist_path, plist_content)
            .with_context(|| format!("writing {}", plist_path.display()))?;
        // Set restrictive permissions on the plist file.
        set_private_permissions(&plist_path)?;

        println!("created launchd plist at {}", plist_path.display());
        println!("run: launchctl load {}", plist_path.display());
    }

    #[cfg(target_os = "linux")]
    {
        let desktop_content = format_desktop_entry(&args.join(" "));
        let autostart_dir = linux_autostart_dir();
        std::fs::create_dir_all(&autostart_dir)
            .with_context(|| format!("creating {}", autostart_dir.display()))?;
        let desktop_path = autostart_dir.join("llm-proxy.desktop");
        std::fs::write(&desktop_path, desktop_content)
            .with_context(|| format!("writing {}", desktop_path.display()))?;
        // Set restrictive permissions on the desktop entry.
        set_private_permissions(&desktop_path)?;
        println!("created desktop entry at {}", desktop_path.display());
    }

    #[cfg(not(any(target_os = "macos", target_os = "linux")))]
    {
        println!("auto-start is not supported on this platform");
        println!("add this command to your shell startup script:");
        println!("  {}", args.join(" "));
    }

    Ok(())
}

/// Run the `autostart disable` command.
fn cmd_autostart_disable() -> Result<()> {
    #[cfg(target_os = "macos")]
    {
        let plist_path = launchd_plist_path();

        if plist_path.exists() {
            let _ = std::process::Command::new("launchctl")
                .args(["unload", &plist_path.to_string_lossy()])
                .output();
            std::fs::remove_file(&plist_path)
                .with_context(|| format!("removing {}", plist_path.display()))?;
            println!("removed launchd plist");
        } else {
            println!("no launchd plist found");
        }
    }

    #[cfg(target_os = "linux")]
    {
        let autostart_dir = linux_autostart_dir();
        let desktop_path = autostart_dir.join("llm-proxy.desktop");
        if desktop_path.exists() {
            std::fs::remove_file(&desktop_path)
                .with_context(|| format!("removing {}", desktop_path.display()))?;
            println!("removed desktop entry");
        } else {
            println!("no desktop entry found");
        }
    }

    #[cfg(not(any(target_os = "macos", target_os = "linux")))]
    {
        println!("auto-start is not supported on this platform");
    }

    Ok(())
}

/// Run the `autostart status` command.
fn cmd_autostart_status() -> Result<()> {
    #[cfg(target_os = "macos")]
    {
        let plist_path = launchd_plist_path();

        if plist_path.exists() {
            println!("auto-start is enabled ({})", plist_path.display());
        } else {
            println!("auto-start is disabled (no launchd plist found)");
        }
    }

    #[cfg(target_os = "linux")]
    {
        let autostart_dir = linux_autostart_dir();
        let desktop_path = autostart_dir.join("llm-proxy.desktop");
        if desktop_path.exists() {
            println!("auto-start is enabled ({})", desktop_path.display());
        } else {
            println!("auto-start is disabled (no desktop entry found)");
        }
    }

    #[cfg(not(any(target_os = "macos", target_os = "linux")))]
    {
        println!("auto-start is not supported on this platform");
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Platform-specific helpers
// ---------------------------------------------------------------------------

/// Generate a macOS launchd plist for auto-start.
///
/// The `command` string is XML-escaped to prevent malformed plists when the
/// executable path contains XML special characters (<, >, &, ", ').
#[cfg(target_os = "macos")]
fn format_plist(command: &str) -> String {
    let escaped_command = xml_escape(command);
    let log_path = config_dir().join("llm-proxy.log").display().to_string();
    let escaped_log = xml_escape(&log_path);
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.llm-proxy</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>-c</string>
        <string>{escaped_command}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>{escaped_log}</string>
    <key>StandardErrorPath</key>
    <string>{escaped_log}</string>
</dict>
</plist>
"#
    )
}

/// Generate a Linux XDG desktop entry for auto-start.
///
/// The `command` string is desktop-entry-escaped for the Exec key.
#[cfg(target_os = "linux")]
fn format_desktop_entry(command: &str) -> String {
    // Desktop entry Exec values need minimal escaping per the spec.
    // In practice, the command is built from paths that rarely contain
    // special characters, but we still escape newlines to prevent
    // multi-line injection.
    let escaped = command.replace('\\', "\\\\").replace('\n', "\\n");
    format!(
        r#"[Desktop Entry]
Type=Application
Name=LLM Proxy
Exec={escaped}
X-GNOME-Autostart-enabled=true
Hidden=false
"#
    )
}

/// Escape a string for safe inclusion in XML content.
///
/// Replaces the five predefined XML entities: `<`, `>`, `&`, `"`, `'`.
fn xml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(ch),
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Load TOML config files and build [`AppState`] in TOML new-runtime mode.
///
/// Loads the main `AppConfig` from `path`, then scans a `providers/` directory
/// next to `path` for provider TOML files. Uses [`ProviderRegistry::load_from_dir`]
/// which handles non-regular-file filtering, deterministic sorted ordering, and
/// duplicate-name detection. Protocol validation is performed separately against
/// the builtin adapter set after loading.
///
/// Takes ownership of `adapter_registry` and `proxy_client` since they are
/// consumed by [`AppState::new`] and not reused after this call.
fn load_toml_state(
    path: &std::path::Path,
    adapter_registry: ProviderAdapterRegistry,
    proxy_client: ProxyClient,
    port_override: Option<u16>,
) -> Result<AppState> {
    let mut app_config: AppConfig = load_app_config(path)
        .with_context(|| format!("loading TOML config from {}", path.display()))?;

    // Apply CLI port override.
    // In-place mutation is safe here: the config is consumed by AppState::new
    // below and is not shared with any other caller.
    if let Some(p) = port_override {
        let mut bind = app_config.server.bind;
        bind.set_port(p);
        app_config.server.bind = bind;
    }

    // Load provider files from providers/ directory next to the main config.
    let providers_dir = providers_dir_for(path);
    let registry = if providers_dir.exists() {
        ProviderRegistry::load_from_dir(&providers_dir)
            .with_context(|| format!("loading providers from {}", providers_dir.display()))?
    } else {
        ProviderRegistry::from_providers(vec![])
            .with_context(|| "building empty provider registry")?
    };

    // Validate all provider protocols against the builtin adapter set.
    let known_protocols = adapter_registry.protocol_names();
    registry
        .validate_protocols(known_protocols)
        .with_context(|| "validating provider protocols")?;

    info!(
        config = %path.display(),
        providers = registry.len(),
        "loaded TOML config"
    );

    Ok(AppState::new(
        app_config,
        registry,
        adapter_registry,
        proxy_client,
        build_info(),
    ))
}

fn build_info() -> BuildInfo {
    BuildInfo {
        name: env!("CARGO_PKG_NAME"),
        version: env!("CARGO_PKG_VERSION"),
        target: env!("VERGEN_CARGO_TARGET_TRIPLE"),
        git_sha: env!("VERGEN_GIT_SHA"),
    }
}

fn init_tracing() {
    use tracing_subscriber::{EnvFilter, fmt, layer::SubscriberExt, util::SubscriberInitExt};
    // Fallback to "info" level when RUST_LOG is not set. "info" is a known-valid
    // filter string so parse_lossy is safe here (it never panics).
    let filter = EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| EnvFilter::builder().parse_lossy("info"));
    tracing_subscriber::registry()
        .with(filter)
        .with(fmt::layer())
        .init();
}

// ---------------------------------------------------------------------------
// home_env helper (minimal, no external dep)
// ---------------------------------------------------------------------------

/// Minimal home-directory resolution without depending on the `dirs` crate.
///
/// Checks `$HOME` (macOS/Linux) and `$USERPROFILE` (Windows) only.
/// Does not fall back to `getpwuid()` or XDG defaults. This is intentional:
/// the `dirs` crate is avoided to minimize dependency tree, and these two
/// env vars cover all standard configurations.
mod home_env {
    use std::path::PathBuf;

    /// Returns the user's home directory.
    pub(crate) fn home_dir() -> Option<PathBuf> {
        std::env::var("HOME")
            .or_else(|_| std::env::var("USERPROFILE"))
            .ok()
            .map(PathBuf::from)
    }
}

// ---------------------------------------------------------------------------
// File permissions helper
// ---------------------------------------------------------------------------

/// Set owner-only read/write permissions (0600) on a file.
///
/// Used for config and autostart files that reference API keys via
/// environment variables. On non-Unix platforms this is a no-op.
fn set_private_permissions(path: &std::path::Path) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
            .with_context(|| format!("setting permissions on {}", path.display()))?;
    }
    #[cfg(not(unix))]
    {
        let _ = path;
    }
    Ok(())
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    /// Crate-level mutex for serialising tests that mutate environment variables.
    static TEST_ENV_MUTEX: Mutex<()> = Mutex::new(());

    /// RAII wrapper that holds the test env mutex lock.
    struct TestEnvLock {
        _guard: std::sync::MutexGuard<'static, ()>,
    }

    impl TestEnvLock {
        fn acquire() -> Self {
            let guard = TEST_ENV_MUTEX.lock().unwrap_or_else(|e| e.into_inner());
            Self { _guard: guard }
        }
    }

    // -- Env var test helpers --------------------------------------------------

    /// Guard that restores an env var on drop. NOT thread-safe; tests using
    /// this must be serialised via `TestEnvLock`.
    struct EnvGuard {
        key: String,
        original: Option<String>,
    }

    impl EnvGuard {
        fn set(key: &str, value: &str) -> Self {
            let original = std::env::var(key).ok();
            // SAFETY: This call is safe because:
            // 1. All tests using EnvGuard are serialised via TEST_ENV_MUTEX,
            //    so no concurrent access to environment variables occurs.
            // 2. The original value is captured and restored on drop.
            // 3. This only runs in test code, not in production.
            unsafe {
                std::env::set_var(key, value);
            }
            Self {
                key: key.to_owned(),
                original,
            }
        }

        fn remove(key: &str) -> Self {
            let original = std::env::var(key).ok();
            // SAFETY: Same justification as set() above -- serialised via
            // TEST_ENV_MUTEX and original value is restored on drop.
            unsafe {
                std::env::remove_var(key);
            }
            Self {
                key: key.to_owned(),
                original,
            }
        }
    }

    impl Drop for EnvGuard {
        fn drop(&mut self) {
            // SAFETY: Same justification as set()/remove() above --
            // serialised via TEST_ENV_MUTEX.
            match &self.original {
                Some(v) => unsafe {
                    std::env::set_var(&self.key, v);
                },
                None => unsafe {
                    std::env::remove_var(&self.key);
                },
            }
        }
    }

    /// Holds the mutex lock and env-var guards together.
    struct EnvScope {
        _lock: TestEnvLock,
        _guards: Vec<EnvGuard>,
    }

    /// Clean all config-related env vars and return scope.
    fn clean_config_env() -> EnvScope {
        let lock = TestEnvLock::acquire();
        let guards = vec![
            EnvGuard::remove("LLM_PROXY_CONFIG"),
            EnvGuard::remove("OC_GO_CC_CONFIG"),
            EnvGuard::remove("LLM_PROXY_OPENCODE_GO_KEY"),
            EnvGuard::remove("LLM_PROXY_OPENCODE_ZEN_KEY"),
        ];
        EnvScope {
            _lock: lock,
            _guards: guards,
        }
    }

    // =========================================================================
    // Phase 10 tests
    // =========================================================================

    // -- config path resolution prefers CLI path --------------------------------

    #[test]
    fn config_path_resolution_prefers_cli_path() {
        let _env = clean_config_env();
        let cli_path = PathBuf::from("/tmp/my-custom-config.toml");
        let (resolved, legacy) = resolve_serve_config(Some(cli_path.as_path()));
        assert_eq!(resolved, cli_path);
        assert!(!legacy, "CLI path should not trigger legacy detection");
    }

    // -- config path resolution supports $LLM_PROXY_CONFIG ----------------------

    #[test]
    fn config_path_resolution_supports_llm_proxy_config() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("LLM_PROXY_CONFIG", "/tmp/from-env.toml");
        let (resolved, legacy) = resolve_serve_config(None);
        assert_eq!(resolved, PathBuf::from("/tmp/from-env.toml"));
        assert!(
            !legacy,
            "LLM_PROXY_CONFIG should not trigger legacy detection"
        );
    }

    // -- CLI path wins over $LLM_PROXY_CONFIG -----------------------------------

    #[test]
    fn cli_path_wins_over_llm_proxy_config() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("LLM_PROXY_CONFIG", "/tmp/from-env.toml");
        let cli_path = PathBuf::from("/tmp/cli-path.toml");
        let (resolved, _) = resolve_serve_config(Some(cli_path.as_path()));
        assert_eq!(resolved, cli_path);
    }

    // -- $OC_GO_CC_CONFIG alone detected as legacy ------------------------------

    #[test]
    fn oc_go_cc_config_alone_detected_as_legacy() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("OC_GO_CC_CONFIG", "/tmp/old-config.json");
        let (_, legacy) = resolve_serve_config(None);
        assert!(
            legacy,
            "OC_GO_CC_CONFIG alone should trigger legacy detection"
        );
    }

    // -- explicit TOML --config wins over $OC_GO_CC_CONFIG ----------------------

    #[test]
    fn explicit_toml_config_wins_over_oc_go_cc_config() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("OC_GO_CC_CONFIG", "/tmp/old-config.json");
        let cli_path = PathBuf::from("/tmp/new-config.toml");
        let (resolved, legacy) = resolve_serve_config(Some(cli_path.as_path()));
        assert_eq!(resolved, cli_path);
        assert!(!legacy, "explicit CLI path should not trigger legacy");
    }

    // -- $LLM_PROXY_CONFIG wins over $OC_GO_CC_CONFIG ---------------------------

    #[test]
    fn llm_proxy_config_wins_over_oc_go_cc_config() {
        let _env = clean_config_env();
        let _g1 = EnvGuard::set("LLM_PROXY_CONFIG", "/tmp/new.toml");
        let _g2 = EnvGuard::set("OC_GO_CC_CONFIG", "/tmp/old.json");
        let (resolved, legacy) = resolve_serve_config(None);
        assert_eq!(resolved, PathBuf::from("/tmp/new.toml"));
        assert!(!legacy, "LLM_PROXY_CONFIG should win over OC_GO_CC_CONFIG");
    }

    // -- provider directory path is next to config file -------------------------

    #[test]
    fn provider_directory_path_is_next_to_config_file() {
        let config_path = PathBuf::from("/home/user/.config/llm-proxy/config.toml");
        let providers = providers_dir_for(&config_path);
        assert_eq!(
            providers,
            PathBuf::from("/home/user/.config/llm-proxy/providers")
        );
    }

    // -- provider directory path with no parent uses current dir ----------------

    #[test]
    fn provider_directory_path_with_no_parent_uses_current_dir() {
        let config_path = PathBuf::from("config.toml");
        let providers = providers_dir_for(&config_path);
        // Path::new("config.toml").parent() returns Some(""), and "".join("providers") = "providers"
        assert_eq!(providers, PathBuf::from("providers"));
    }

    // -- generated TOML parses as AppConfig ------------------------------------

    #[test]
    fn generated_toml_parses_as_app_config() {
        let _env = clean_config_env();
        use llm_proxy_core::load_app_config;
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("config.toml");
        std::fs::write(&path, DEFAULT_CONFIG_TOML).expect("write");
        let cfg = load_app_config(&path).expect("generated TOML should parse as AppConfig");
        assert!(
            cfg.models.is_empty(),
            "generated config should have no global model routes (server settings only)"
        );
    }

    // -- generated provider TOML parses as ProviderFile -------------------------

    #[test]
    fn generated_provider_toml_parses_as_provider_file() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("LLM_PROXY_OPENCODE_GO_KEY", "test-key");
        use llm_proxy_core::load_provider_config;
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("opencode-go.toml");
        std::fs::write(&path, DEFAULT_PROVIDER_OPENCODE_GO).expect("write");
        let cfg = load_provider_config(&path, None).expect("generated provider TOML should parse");
        assert_eq!(cfg.name, "opencode-go");
        assert!(!cfg.adapters.is_empty());
        assert!(!cfg.models.is_empty());
    }

    // -- generated provider TOML parses as ProviderFile (zen) -------------------

    #[test]
    fn generated_zen_provider_toml_parses_as_provider_file() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("LLM_PROXY_OPENCODE_ZEN_KEY", "test-key");
        use llm_proxy_core::load_provider_config;
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("opencode-zen.toml");
        std::fs::write(&path, DEFAULT_PROVIDER_OPENCODE_ZEN).expect("write");
        let cfg =
            load_provider_config(&path, None).expect("generated zen provider TOML should parse");
        assert_eq!(cfg.name, "opencode-zen");
        assert_eq!(cfg.adapters.len(), 4, "zen should have 4 adapters");
    }

    // -- generated config plus providers pass full validation -------------------

    #[test]
    fn generated_config_plus_providers_pass_full_validation() {
        let _env = clean_config_env();
        let _g1 = EnvGuard::set("LLM_PROXY_OPENCODE_GO_KEY", "test-go-key");
        let _g2 = EnvGuard::set("LLM_PROXY_OPENCODE_ZEN_KEY", "test-zen-key");

        use llm_proxy_core::{ProviderRegistry, load_app_config};

        let dir = tempfile::tempdir().expect("tempdir");

        // Write main config.
        let config_path = dir.path().join("config.toml");
        std::fs::write(&config_path, DEFAULT_CONFIG_TOML).expect("write config");

        // Create providers dir and write provider files.
        let providers_dir = dir.path().join("providers");
        std::fs::create_dir_all(&providers_dir).expect("mkdir providers");

        std::fs::write(
            providers_dir.join("opencode-go.toml"),
            DEFAULT_PROVIDER_OPENCODE_GO,
        )
        .expect("write go provider");
        std::fs::write(
            providers_dir.join("opencode-zen.toml"),
            DEFAULT_PROVIDER_OPENCODE_ZEN,
        )
        .expect("write zen provider");

        // Load and validate.
        let _app_config = load_app_config(&config_path).expect("load app config");
        let registry = ProviderRegistry::load_from_dir(&providers_dir).expect("load providers");

        // Validate protocols against builtins.
        let adapter_registry = ProviderAdapterRegistry::builtin();
        registry
            .validate_protocols(adapter_registry.protocol_names())
            .expect("protocol validation should pass");

        assert_eq!(registry.len(), 2, "should have 2 providers");
    }

    // -- every generated provider model route resolves --------------------------

    #[test]
    fn every_generated_provider_model_route_resolves() {
        let _env = clean_config_env();
        let _g1 = EnvGuard::set("LLM_PROXY_OPENCODE_GO_KEY", "test-go-key");
        let _g2 = EnvGuard::set("LLM_PROXY_OPENCODE_ZEN_KEY", "test-zen-key");

        use llm_proxy_core::ProviderRegistry;

        let dir = tempfile::tempdir().expect("tempdir");

        let providers_dir = dir.path().join("providers");
        std::fs::create_dir_all(&providers_dir).expect("mkdir providers");
        std::fs::write(
            providers_dir.join("opencode-go.toml"),
            DEFAULT_PROVIDER_OPENCODE_GO,
        )
        .expect("write go provider");
        std::fs::write(
            providers_dir.join("opencode-zen.toml"),
            DEFAULT_PROVIDER_OPENCODE_ZEN,
        )
        .expect("write zen provider");

        let registry = ProviderRegistry::load_from_dir(&providers_dir).expect("load providers");

        // Verify every provider model's adapter reference resolves to a valid adapter
        // with a non-empty protocol.
        for provider in registry.iter() {
            for (model_name, model_cfg) in &provider.models {
                let adapter = provider
                    .adapters
                    .get(&model_cfg.adapter)
                    .unwrap_or_else(|| {
                        panic!(
                            "provider \"{}\": model \"{}\" references unknown adapter \"{}\"",
                            provider.name, model_name, model_cfg.adapter
                        )
                    });
                assert!(
                    !adapter.protocol.is_empty(),
                    "protocol should not be empty for {}/{}",
                    provider.name,
                    model_name
                );
            }
        }
    }

    // -- serve --config old.json exits before constructing AppState -------------

    #[test]
    fn serve_json_config_exits_before_constructing_app_state() {
        let json_path = PathBuf::from("/tmp/old-config.json");
        assert!(is_json_config(&json_path));
        let toml_path = PathBuf::from("/tmp/config.toml");
        assert!(!is_json_config(&toml_path));
    }

    // -- Integration: serve --config old.json bails via validate_toml_extension --

    #[test]
    fn serve_json_config_bails_with_migration_error() {
        let json_path = PathBuf::from("/tmp/old-config.json");
        let result = validate_toml_extension(&json_path);
        assert!(result.is_err(), "JSON path should be rejected");
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("JSON") && err.contains("llm-proxy init"),
            "error should contain migration guidance, got: {err}"
        );
        assert!(
            err.contains("TOML"),
            "error should mention TOML, got: {err}"
        );
    }

    // -- Integration: OC_GO_CC_CONFIG alone triggers legacy and error -----------

    #[test]
    fn oc_go_cc_config_alone_triggers_migration_error() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("OC_GO_CC_CONFIG", "/tmp/old.json");
        let (_, legacy) = resolve_serve_config(None);
        assert!(legacy, "should detect legacy env");
        assert!(
            MIGRATION_ERROR.contains("JSON") && MIGRATION_ERROR.contains("llm-proxy init"),
            "MIGRATION_ERROR should reference JSON and llm-proxy init"
        );
    }

    // -- Integration: resolve_serve_config with legacy env + JSON path bails ----

    #[test]
    fn legacy_env_with_json_config_bails_on_validate() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("OC_GO_CC_CONFIG", "/tmp/old-config.json");
        let (path, legacy) = resolve_serve_config(None);
        assert!(legacy, "OC_GO_CC_CONFIG should set legacy=true");
        let result = validate_toml_extension(&path);
        assert!(result.is_err(), "JSON path should be rejected");
    }

    // -- explicit TOML --config wins over $OC_GO_CC_CONFIG (no migration error) -

    #[test]
    fn explicit_toml_over_oc_go_cc_config_no_migration_error() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("OC_GO_CC_CONFIG", "/tmp/old.json");
        let (resolved, legacy) =
            resolve_serve_config(Some(std::path::Path::new("/tmp/config.toml")));
        assert!(
            !legacy,
            "explicit --config should suppress legacy detection"
        );
        assert!(is_toml_config(&resolved));
    }

    // -- $LLM_PROXY_CONFIG wins over $OC_GO_CC_CONFIG (no migration error) ------

    #[test]
    fn llm_proxy_config_over_oc_go_cc_config_no_migration_error() {
        let _env = clean_config_env();
        let _g1 = EnvGuard::set("LLM_PROXY_CONFIG", "/tmp/config.toml");
        let _g2 = EnvGuard::set("OC_GO_CC_CONFIG", "/tmp/old.json");
        let (_, legacy) = resolve_serve_config(None);
        assert!(!legacy, "LLM_PROXY_CONFIG should suppress legacy detection");
    }

    // -- models lists provider-scoped models -------------------------------------

    #[test]
    fn models_lists_provider_scoped_models() {
        let _env = clean_config_env();
        use llm_proxy_core::ProviderRegistry;

        let dir = tempfile::tempdir().expect("tempdir");

        // Write a provider with 2 models.
        let providers_dir = dir.path().join("providers");
        std::fs::create_dir_all(&providers_dir).expect("mkdir providers");

        let _g = EnvGuard::set("LLM_PROXY_TEST_PROVIDER_KEY", "test-key");
        let provider_toml = r#"
[provider]
name = "test-provider"
api_key = "${LLM_PROXY_TEST_PROVIDER_KEY}"
auth_style = "bearer"

[provider.adapters.chat]
protocol = "openai_chat_completions"
endpoint = "https://example.com/v1/chat/completions"

[provider.models]
"my-model-a" = { adapter = "chat" }
"my-model-b" = { adapter = "chat" }
"#;
        std::fs::write(providers_dir.join("test-provider.toml"), provider_toml).expect("write");

        let registry = ProviderRegistry::load_from_dir(&providers_dir).expect("load");
        let provider = registry.get("test-provider").expect("provider");
        assert_eq!(provider.models.len(), 2);
        assert!(provider.models.contains_key("my-model-a"));
        assert!(provider.models.contains_key("my-model-b"));
    }

    // -- provider models map to correct adapters ---------------------------------

    #[test]
    fn provider_models_map_to_correct_adapters() {
        let _env = clean_config_env();
        use llm_proxy_core::ProviderRegistry;

        let dir = tempfile::tempdir().expect("tempdir");
        let providers_dir = dir.path().join("providers");
        std::fs::create_dir_all(&providers_dir).expect("mkdir providers");

        let _g = EnvGuard::set("LLM_PROXY_TEST_PROVIDER_KEY", "test-key");
        let provider_toml = r#"
[provider]
name = "test-provider"
api_key = "${LLM_PROXY_TEST_PROVIDER_KEY}"
auth_style = "bearer"

[provider.adapters.chat]
protocol = "openai_chat_completions"
endpoint = "https://example.com/v1/chat/completions"

[provider.adapters.messages]
protocol = "anthropic_messages"
endpoint = "https://example.com/v1/messages"

[provider.models]
"fast-model" = { adapter = "chat" }
"claude-model" = { adapter = "messages" }
"#;
        std::fs::write(providers_dir.join("test-provider.toml"), provider_toml).expect("write");

        let registry = ProviderRegistry::load_from_dir(&providers_dir).expect("load");
        let provider = registry.get("test-provider").expect("provider");
        assert_eq!(provider.models["fast-model"].adapter, "chat");
        assert_eq!(provider.models["claude-model"].adapter, "messages");
    }

    // -- generated config contains no sampling overrides ------------------------

    #[test]
    fn generated_config_contains_no_sampling_overrides() {
        // Verify the generated TOML does not contain sampling/tool/reasoning
        // cache/stream override keys.
        assert!(
            !DEFAULT_CONFIG_TOML.contains("temperature"),
            "generated config must not contain temperature"
        );
        assert!(
            !DEFAULT_CONFIG_TOML.contains("top_p"),
            "generated config must not contain top_p"
        );
        assert!(
            !DEFAULT_CONFIG_TOML.contains("max_tokens"),
            "generated config must not contain max_tokens"
        );
    }

    // -- generated config contains no tool/reasoning/cache/stream overrides -----

    #[test]
    fn generated_config_contains_no_tool_reasoning_cache_stream_overrides() {
        assert!(
            !DEFAULT_CONFIG_TOML.contains("tools"),
            "generated config must not contain tools"
        );
        assert!(
            !DEFAULT_CONFIG_TOML.contains("reasoning"),
            "generated config must not contain reasoning"
        );
        assert!(
            !DEFAULT_CONFIG_TOML.contains("thinking"),
            "generated config must not contain thinking"
        );
        assert!(
            !DEFAULT_CONFIG_TOML.contains("cache"),
            "generated config must not contain cache"
        );
        // "stream" appears in "upstream_model", so check for specific patterns only.
        assert!(
            !DEFAULT_CONFIG_TOML.contains("stream_override"),
            "generated config must not contain stream overrides"
        );
        assert!(
            !DEFAULT_CONFIG_TOML.contains("streaming"),
            "generated config must not contain streaming settings"
        );
    }

    // -- init writes no fallback/scenario JSON ----------------------------------

    #[test]
    fn init_writes_no_fallback_scenario_json() {
        assert!(
            !DEFAULT_CONFIG_TOML.contains("fallback"),
            "generated config must not contain fallback"
        );
        assert!(
            !DEFAULT_CONFIG_TOML.contains("scenario"),
            "generated config must not contain scenario"
        );
        // Also verify the config file extension is .toml, not .json.
        assert!(
            default_config_path()
                .extension()
                .is_some_and(|e| e == "toml")
        );
    }

    // -- validate rejects legacy scenario config --------------------------------

    #[test]
    fn validate_rejects_legacy_json_config() {
        let json_path = PathBuf::from("/tmp/old-config.json");
        // Verify the full validation path rejects JSON with migration error.
        let result = validate_toml_extension(&json_path);
        assert!(result.is_err(), "JSON config should be rejected");
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("JSON") && err.contains("llm-proxy init"),
            "error should contain migration guidance, got: {err}"
        );
    }

    // -- validate rejects non-toml extension ------------------------------------

    #[test]
    fn validate_rejects_non_toml_extension() {
        let yaml_path = PathBuf::from("/tmp/config.yaml");
        assert!(
            !is_toml_config(&yaml_path),
            "YAML config should be rejected"
        );
        assert!(
            !is_json_config(&yaml_path),
            "YAML should not match JSON check"
        );
    }

    // -- is_json_config edge cases -----------------------------------------------

    #[test]
    fn is_json_config_case_insensitive() {
        assert!(is_json_config(&PathBuf::from("config.JSON")));
        assert!(is_json_config(&PathBuf::from("config.Json")));
    }

    #[test]
    fn is_toml_config_case_insensitive() {
        assert!(is_toml_config(&PathBuf::from("config.TOML")));
        assert!(is_toml_config(&PathBuf::from("config.Toml")));
    }

    #[test]
    fn no_extension_is_not_json_or_toml() {
        let path = PathBuf::from("/tmp/config");
        assert!(!is_json_config(&path));
        assert!(!is_toml_config(&path));
    }

    // -- resolve_config for validate/models prefers CLI -------------------------

    #[test]
    fn resolve_config_prefers_cli() {
        let _env = clean_config_env();
        let cli = PathBuf::from("/custom/path.toml");
        let resolved = resolve_config(Some(cli.as_path()));
        assert_eq!(resolved, cli);
    }

    #[test]
    fn resolve_config_uses_llm_proxy_config() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("LLM_PROXY_CONFIG", "/from/env.toml");
        let resolved = resolve_config(None);
        assert_eq!(resolved, PathBuf::from("/from/env.toml"));
    }

    #[test]
    fn resolve_config_cli_wins_over_env() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("LLM_PROXY_CONFIG", "/from/env.toml");
        let cli = PathBuf::from("/cli/path.toml");
        let resolved = resolve_config(Some(cli.as_path()));
        assert_eq!(resolved, cli);
    }

    // -- default_config_path returns .toml --------------------------------------

    #[test]
    fn default_config_path_returns_toml() {
        let path = default_config_path();
        assert!(is_toml_config(&path));
        assert!(path.to_string_lossy().contains("config.toml"));
    }

    // -- migration error message is correct -------------------------------------

    #[test]
    fn migration_error_message() {
        assert!(
            MIGRATION_ERROR.contains("JSON"),
            "migration error should mention JSON"
        );
        assert!(
            MIGRATION_ERROR.contains("oc-go-cc"),
            "migration error should mention oc-go-cc"
        );
        assert!(
            MIGRATION_ERROR.contains("llm-proxy init"),
            "migration error should mention llm-proxy init"
        );
        assert!(
            MIGRATION_ERROR.contains("TOML"),
            "migration error should mention TOML"
        );
    }

    // -- generated provider files have correct adapter counts --------------------

    #[test]
    fn generated_opencode_go_provider_has_correct_adapters() {
        // opencode-go should have chat + anthropic adapters
        assert!(DEFAULT_PROVIDER_OPENCODE_GO.contains("openai_chat_completions"));
        assert!(DEFAULT_PROVIDER_OPENCODE_GO.contains("anthropic_messages"));
    }

    #[test]
    fn generated_opencode_zen_provider_has_four_adapters() {
        assert!(DEFAULT_PROVIDER_OPENCODE_ZEN.contains("openai_chat_completions"));
        assert!(DEFAULT_PROVIDER_OPENCODE_ZEN.contains("anthropic_messages"));
        assert!(DEFAULT_PROVIDER_OPENCODE_ZEN.contains("openai_responses"));
        assert!(DEFAULT_PROVIDER_OPENCODE_ZEN.contains("gemini_generate_content"));
    }

    // -- init does not write .json files ----------------------------------------

    #[test]
    fn init_does_not_write_json_files() {
        // Verify that none of the generated content mentions .json extensions
        // and all generated files are .toml
        assert!(!DEFAULT_CONFIG_TOML.contains(".json"));
        assert!(!DEFAULT_PROVIDER_OPENCODE_GO.contains(".json"));
        assert!(!DEFAULT_PROVIDER_OPENCODE_ZEN.contains(".json"));
    }

    // -- generated provider files reference only declared adapters ---------------

    #[test]
    fn generated_provider_models_reference_only_declared_adapters() {
        let _env = clean_config_env();
        let _g1 = EnvGuard::set("LLM_PROXY_OPENCODE_GO_KEY", "test-key");
        let _g2 = EnvGuard::set("LLM_PROXY_OPENCODE_ZEN_KEY", "test-key");
        use llm_proxy_core::load_provider_config;

        let dir = tempfile::tempdir().expect("tempdir");

        let go_path = dir.path().join("opencode-go.toml");
        std::fs::write(&go_path, DEFAULT_PROVIDER_OPENCODE_GO).expect("write");
        let go = load_provider_config(&go_path, None).expect("go provider should parse");

        let zen_path = dir.path().join("opencode-zen.toml");
        std::fs::write(&zen_path, DEFAULT_PROVIDER_OPENCODE_ZEN).expect("write");
        let zen = load_provider_config(&zen_path, None).expect("zen provider should parse");

        // Every model adapter reference should exist in the provider's adapter map.
        for (model, cfg) in &go.models {
            assert!(
                go.adapters.contains_key(&cfg.adapter),
                "opencode-go: model \"{}\" references unknown adapter \"{}\"",
                model,
                cfg.adapter
            );
        }
        for (model, cfg) in &zen.models {
            assert!(
                zen.adapters.contains_key(&cfg.adapter),
                "opencode-zen: model \"{}\" references unknown adapter \"{}\"",
                model,
                cfg.adapter
            );
        }
    }

    // =========================================================================
    // Missing test coverage from audit round 2
    // =========================================================================

    // -- resolve_serve_config falls to default path when no CLI arg and no env vars --

    #[test]
    fn resolve_serve_config_falls_to_default_path() {
        let _env = clean_config_env();
        let (resolved, legacy) = resolve_serve_config(None);
        assert_eq!(resolved, default_config_path());
        assert!(!legacy, "default path should not trigger legacy");
    }

    // -- serve rejects non-TOML, non-JSON extension -------------------------------

    #[test]
    fn serve_rejects_non_toml_non_json_extension() {
        let yaml_path = PathBuf::from("/tmp/config.yaml");
        let result = validate_toml_extension(&yaml_path);
        assert!(result.is_err(), "YAML path should be rejected");
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("unsupported config file extension"),
            "error should mention unsupported extension, got: {err}"
        );

        let txt_path = PathBuf::from("/tmp/config.txt");
        let result = validate_toml_extension(&txt_path);
        assert!(result.is_err(), ".txt path should be rejected");
    }

    // -- models command with empty provider models -------------------------------

    #[test]
    fn models_command_with_empty_provider_models() {
        let _env = clean_config_env();
        use llm_proxy_core::ProviderRegistry;

        let dir = tempfile::tempdir().expect("tempdir");
        let providers_dir = dir.path().join("providers");
        std::fs::create_dir_all(&providers_dir).expect("mkdir providers");

        let _g = EnvGuard::set("LLM_PROXY_TEST_PROVIDER_KEY", "test-key");
        let provider_toml = r#"
[provider]
name = "empty-models-provider"
api_key = "${LLM_PROXY_TEST_PROVIDER_KEY}"
auth_style = "bearer"

[provider.adapters.chat]
protocol = "openai_chat_completions"
endpoint = "https://example.com/v1/chat/completions"

[provider.models]
"#;
        std::fs::write(providers_dir.join("empty.toml"), provider_toml).expect("write");

        let registry = ProviderRegistry::load_from_dir(&providers_dir).expect("load");
        let provider = registry.get("empty-models-provider").expect("provider");
        assert!(
            provider.models.is_empty(),
            "provider with empty [provider.models] should parse with no models"
        );
    }

    // -- validate with no providers directory produces empty registry -------------

    #[test]
    fn validate_with_no_providers_dir_produces_empty_registry() {
        let _env = clean_config_env();

        let dir = tempfile::tempdir().expect("tempdir");
        let config_path = dir.path().join("config.toml");
        std::fs::write(&config_path, DEFAULT_CONFIG_TOML).expect("write config");

        // No providers/ subdirectory -- should still parse main config.
        let app_config = load_app_config(&config_path).expect("load");
        assert!(
            app_config.models.is_empty(),
            "generated config should have no global model routes"
        );
    }

    // -- generated config contains no standalone stream key -----------------------

    #[test]
    fn generated_config_contains_no_stream_override_key() {
        // Check that "stream" does not appear as a standalone TOML key in the
        // generated config. Since the generated config now has only server settings
        // and an empty [models] section, just verify no stream-related keys exist.
        for line in DEFAULT_CONFIG_TOML.lines() {
            let trimmed = line.trim();
            // Skip comments and section headers
            if trimmed.starts_with('#') || trimmed.starts_with('[') || trimmed.is_empty() {
                continue;
            }
            // Check that no key name is "stream"
            if let Some(key) = trimmed.split('=').next() {
                let key = key.trim();
                if key == "stream" {
                    panic!(
                        "generated config must not contain a 'stream' key, \
                         found in line: {trimmed}"
                    );
                }
            }
        }
    }

    // -- example config files are valid TOML -------------------------------------

    #[test]
    fn example_config_file_is_valid_toml() {
        let _env = clean_config_env();
        let example_path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../config.toml.example");
        if example_path.exists() {
            // If the example file has provider entries that require env vars, skip
            // validation and just verify it can be read.
            let _content =
                std::fs::read_to_string(&example_path).expect("example config should be readable");
            // At minimum the file exists and is non-empty.
            assert!(!_content.is_empty(), "example config should not be empty");
        }
        // If the example file doesn't exist, that's also acceptable (generated by init).
    }

    // -- init writes files to a temp directory (integration) ---------------------

    #[test]
    fn init_writes_all_config_files_to_directory() {
        let _env = clean_config_env();
        let dir = tempfile::tempdir().expect("tempdir");
        let base = dir.path();

        let config_path = base.join("config.toml");
        let providers_dir = base.join("providers");

        // Simulate what cmd_init does (without calling it directly since it
        // writes to real config dir).
        std::fs::create_dir_all(&providers_dir).expect("mkdir providers");

        std::fs::write(&config_path, DEFAULT_CONFIG_TOML).expect("write config");
        std::fs::write(
            providers_dir.join("opencode-go.toml"),
            DEFAULT_PROVIDER_OPENCODE_GO,
        )
        .expect("write go provider");
        std::fs::write(
            providers_dir.join("opencode-zen.toml"),
            DEFAULT_PROVIDER_OPENCODE_ZEN,
        )
        .expect("write zen provider");

        assert!(config_path.exists(), "config.toml should exist");
        assert!(
            providers_dir.join("opencode-go.toml").exists(),
            "go provider should exist"
        );
        assert!(
            providers_dir.join("opencode-zen.toml").exists(),
            "zen provider should exist"
        );

        // Verify the files parse correctly.
        let _g1 = EnvGuard::set("LLM_PROXY_OPENCODE_GO_KEY", "test-key");
        let _g2 = EnvGuard::set("LLM_PROXY_OPENCODE_ZEN_KEY", "test-key");

        let cfg = load_app_config(&config_path).expect("config should parse");
        assert!(
            cfg.models.is_empty(),
            "generated config should have no global model routes"
        );

        use llm_proxy_core::load_provider_config;
        let go = load_provider_config(providers_dir.join("opencode-go.toml"), None)
            .expect("go provider should parse");
        assert_eq!(go.name, "opencode-go");

        let zen = load_provider_config(providers_dir.join("opencode-zen.toml"), None)
            .expect("zen provider should parse");
        assert_eq!(zen.name, "opencode-zen");
    }

    // -- xml_escape correctly escapes special characters -------------------------

    #[test]
    fn xml_escape_handles_special_characters() {
        assert_eq!(xml_escape("hello"), "hello");
        assert_eq!(xml_escape("<>&\"'"), "&lt;&gt;&amp;&quot;&apos;");
        assert_eq!(xml_escape("no-special"), "no-special");
        assert_eq!(
            xml_escape("a<b>c&d\"e'f"),
            "a&lt;b&gt;c&amp;d&quot;e&apos;f"
        );
    }

    // -- validate_toml_extension accepts valid TOML path -------------------------

    #[test]
    fn validate_toml_extension_accepts_toml_path() {
        let toml_path = PathBuf::from("/tmp/config.toml");
        assert!(validate_toml_extension(&toml_path).is_ok());
    }

    // =========================================================================
    // Additional test coverage from audit round 3
    // =========================================================================

    // -- resolve_serve_config ignores empty LLM_PROXY_CONFIG ----------------------

    #[test]
    fn resolve_serve_config_with_empty_llm_proxy_config_falls_through() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("LLM_PROXY_CONFIG", "");
        let (resolved, legacy) = resolve_serve_config(None);
        assert_eq!(resolved, default_config_path());
        assert!(
            !legacy,
            "empty LLM_PROXY_CONFIG should fall through to default"
        );
    }

    // -- resolve_serve_config ignores empty OC_GO_CC_CONFIG -----------------------

    #[test]
    fn resolve_serve_config_with_empty_oc_go_cc_config_falls_through() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("OC_GO_CC_CONFIG", "");
        let (resolved, legacy) = resolve_serve_config(None);
        assert_eq!(resolved, default_config_path());
        assert!(
            !legacy,
            "empty OC_GO_CC_CONFIG should fall through to default"
        );
    }

    // -- resolve_config ignores empty LLM_PROXY_CONFIG ---------------------------

    #[test]
    fn resolve_config_with_empty_env_falls_to_default() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("LLM_PROXY_CONFIG", "");
        let resolved = resolve_config(None);
        assert_eq!(resolved, default_config_path());
    }

    // -- resolve_config ignores OC_GO_CC_CONFIG ----------------------------------

    #[test]
    fn resolve_config_ignores_oc_go_cc_config() {
        let _env = clean_config_env();
        let _g = EnvGuard::set("OC_GO_CC_CONFIG", "/tmp/legacy.toml");
        let resolved = resolve_config(None);
        assert_eq!(
            resolved,
            default_config_path(),
            "resolve_config should ignore OC_GO_CC_CONFIG and use default path"
        );
    }

    // -- init refuses to overwrite existing config --------------------------------

    #[test]
    fn init_refuses_to_overwrite_existing_config() {
        let dir = tempfile::tempdir().expect("tempdir");
        // Write a dummy config to simulate an existing file.
        let config_path = dir.path().join("config.toml");
        std::fs::write(&config_path, "# existing config").expect("write");

        // Verify the bail condition logic.
        assert!(config_path.exists(), "config should exist");
        // cmd_init checks `default_config_path()` which uses the real home dir,
        // so we test the logic inline rather than calling cmd_init directly.
        let would_bail = config_path.exists();
        assert!(would_bail, "init should refuse when config already exists");
    }

    // -- validate rejects TOML with legacy scenario fields ------------------------

    #[test]
    fn validate_rejects_toml_with_legacy_scenario_fields() {
        let _env = clean_config_env();
        use llm_proxy_core::load_app_config;

        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("config.toml");

        // Write a TOML file with a legacy [scenario] section.
        let legacy_toml = r#"
[server]
bind = "127.0.0.1:3456"
request_timeout = "300s"
log_level = "info"
hot_reload = false
server_name = "test"

[models]
"my-model" = { provider = "p1" }

[scenario]
name = "legacy-scenario"
"#;
        std::fs::write(&path, legacy_toml).expect("write");

        // AppConfig uses deny_unknown_fields, so unknown keys like [scenario]
        // should cause a parse error.
        let result = load_app_config(&path);
        assert!(
            result.is_err(),
            "TOML with legacy [scenario] field should be rejected, got: {:?}",
            result
        );
    }

    // -- validate rejects TOML with legacy fallback fields ------------------------

    #[test]
    fn validate_rejects_toml_with_legacy_fallback_fields() {
        let _env = clean_config_env();
        use llm_proxy_core::load_app_config;

        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("config.toml");

        let legacy_toml = r#"
[server]
bind = "127.0.0.1:3456"
request_timeout = "300s"
log_level = "info"
hot_reload = false
server_name = "test"

[models]
"my-model" = { provider = "p1" }

[fallback]
model = "fallback-model"
"#;
        std::fs::write(&path, legacy_toml).expect("write");

        let result = load_app_config(&path);
        assert!(
            result.is_err(),
            "TOML with legacy [fallback] field should be rejected, got: {:?}",
            result
        );
    }

    // -- spawn_daemon constructs correct argument list ---------------------------

    #[test]
    fn spawn_daemon_constructs_correct_argument_list() {
        // Verify that spawn_daemon passes --daemonize (not --_daemonize).
        // We test this indirectly by verifying the clap definition accepts
        // --daemonize.
        let cli = Cli::try_parse_from(["llm-proxy", "serve", "--daemonize"]);
        assert!(cli.is_ok(), "--daemonize should be accepted by clap");

        match cli.unwrap().command {
            Commands::Serve { daemonize, .. } => {
                assert!(
                    daemonize,
                    "daemonize should be true when --daemonize is passed"
                );
            }
            _ => panic!("expected Serve command"),
        }
    }

    // -- migration error message includes oc-go-cc -------------------------------

    #[test]
    fn migration_error_includes_oc_go_cc() {
        assert!(
            MIGRATION_ERROR.contains("oc-go-cc"),
            "migration error should reference oc-go-cc, got: {MIGRATION_ERROR}"
        );
        assert!(
            MIGRATION_ERROR.contains("by serve"),
            "migration error should mention 'by serve', got: {MIGRATION_ERROR}"
        );
    }
}
