//! `llm-proxy` binary -- CLI entry point.
//!
//! Multi-command CLI for the LLM proxy server. Uses TOML config exclusively.
//!
//! Commands:
//!
//! - `serve`    Start the proxy server (foreground or daemon)
//! - `stop`     Stop a running daemon
//! - `status`   Check if the server is running
//! - `init`     Create default TOML config and provider files
//! - `validate` Validate TOML config and print provider route table
//! - `models`   List provider-scoped models
//! - `autostart` Manage auto-start on login (enable / disable / status)

use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};
use llm_proxy_core::{
    AppConfig, CatalogFile, CatalogFileMetadata, ProviderConfig, ProviderRegistry, load_app_config,
    merge_catalog, parse_catalog_file,
};
use llm_proxy_provider::{DiscoveryClient, ProviderAdapterRegistry, ProxyClient};
use llm_proxy_server::{
    AppState, BuildInfo, ModelCatalogService, build_router, shutdown_signal, write_catalog_atomic,
};
use tokio::net::TcpListener;
use tracing::info;

// ---------------------------------------------------------------------------
// CLI definitions
// ---------------------------------------------------------------------------

/// LLM proxy server.
#[derive(Parser, Debug)]
#[command(
    name = "llm-proxy",
    version,
    about = "LLM proxy server with provider-scoped routing",
    propagate_version = true
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Start the proxy server.
    Serve {
        /// Path to config file (must be TOML).
        #[arg(short, long)]
        config: Option<PathBuf>,
        /// Override listen port.
        #[arg(short, long)]
        port: Option<u16>,
        /// Run as background daemon.
        #[arg(short, long)]
        background: bool,
        /// Internal: used by daemon child process.
        #[arg(long, hide = true)]
        daemonize: bool,
    },
    /// Stop a running server.
    Stop,
    /// Check if the server is running.
    Status,
    /// Create a default config file.
    Init,
    /// Validate a config file and print settings.
    Validate {
        /// Path to config file (must be TOML).
        #[arg(short, long)]
        config: Option<PathBuf>,
    },
    /// List provider-scoped models.
    Models {
        /// Path to config file (must be TOML).
        #[arg(short, long)]
        config: Option<PathBuf>,
        /// Filter output to a single provider.
        #[arg(long)]
        provider: Option<String>,
        /// Fetch models from the configured provider discovery endpoint.
        #[arg(long)]
        live: bool,
        /// Persist a successful live result under providers/.catalog/.
        #[arg(long, requires = "live")]
        write_catalog: bool,
        /// Return an error instead of falling back when live discovery fails.
        #[arg(long, requires = "live")]
        require_success: bool,
    },
    /// Manage auto-start on login.
    Autostart {
        #[command(subcommand)]
        action: AutostartAction,
    },
}

#[derive(Subcommand, Debug)]
enum AutostartAction {
    /// Enable auto-start.
    Enable {
        /// Path to config file.
        #[arg(short, long)]
        config: Option<PathBuf>,
        /// Port to listen on.
        #[arg(short, long)]
        port: Option<u16>,
    },
    /// Disable auto-start.
    Disable,
    /// Show auto-start status.
    Status,
}

// ---------------------------------------------------------------------------
// Default TOML config content
// ---------------------------------------------------------------------------

/// Default main config TOML content generated by `llm-proxy init`.
///
/// Contains server settings only. Provider routing is configured in
/// individual provider TOML files under `providers/`. Does NOT include:
/// - sampling overrides (temperature, top_p, etc.)
/// - tool overrides
/// - reasoning/thinking overrides
/// - cache settings
/// - stream overrides
/// - fallback/scenario logic
const DEFAULT_CONFIG_TOML: &str = r#"[server]
bind = "127.0.0.1:3456"
request_timeout = "300s"
log_level = "info"
hot_reload = false
rate_limit_rpm = 100
trust_forwarded_headers = false
dedup_window = "0ms"
server_name = "llm-proxy"
"#;

/// Default provider TOML for opencode-go.
///
/// Uses provider-based routing: inbound route kinds (chat completions,
/// messages) are mapped to adapters in `[provider.routes]`.
const DEFAULT_PROVIDER_OPENCODE_GO: &str = r#"[provider]
name = "opencode-go"
api_key = "${LLM_PROXY_OPENCODE_GO_KEY}"
auth_style = "bearer"

[provider.adapters.chat]
protocol = "openai_chat_completions"
endpoint = "https://opencode.ai/zen/go/v1/chat/completions"

[provider.adapters.anthropic]
protocol = "anthropic_messages"
endpoint = "https://opencode.ai/zen/go/v1/messages"

[provider.routes]
chat_completions = "chat"
messages = "anthropic"

# [provider.model_aliases]
# "alias" = "upstream-model-id"

# [provider.discovery]
# kind = "openai_compatible_models"
# endpoint = "https://opencode.ai/zen/go/v1/models"
# max_pages = 100
# max_models = 20000
# max_response_bytes = 4194304
"#;

/// Default provider TOML for opencode-zen.
///
/// Uses provider-based routing: inbound route kinds (chat completions,
/// messages) are mapped to adapters in `[provider.routes]`.
const DEFAULT_PROVIDER_OPENCODE_ZEN: &str = r#"[provider]
name = "opencode-zen"
api_key = "${LLM_PROXY_OPENCODE_ZEN_KEY}"
auth_style = "bearer"

[provider.adapters.chat]
protocol = "openai_chat_completions"
endpoint = "https://opencode.ai/zen/v1/chat/completions"

[provider.adapters.anthropic]
protocol = "anthropic_messages"
endpoint = "https://opencode.ai/zen/v1/messages"

[provider.adapters.responses]
protocol = "openai_responses"
endpoint = "https://opencode.ai/zen/v1/responses"

[provider.adapters.gemini]
protocol = "gemini_generate_content"
endpoint = "https://opencode.ai/zen/v1/models/{model}:generateContent"

[provider.routes]
chat_completions = "chat"
messages = "anthropic"

# [provider.model_aliases]
# "alias" = "upstream-model-id"

# [provider.discovery]
# kind = "openai_compatible_models"
# endpoint = "https://opencode.ai/zen/v1/models"
# max_pages = 100
# max_models = 20000
# max_response_bytes = 4194304
"#;

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

/// Config directory: `~/.config/llm-proxy/`.
///
/// Falls back to `./.config/llm-proxy/` (relative to current working directory)
/// when `$HOME` and `$USERPROFILE` are both unset. This is unlikely in practice
/// but avoids a panic.
fn config_dir() -> PathBuf {
    home_env::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".config")
        .join("llm-proxy")
}

/// Config file path: `~/.config/llm-proxy/config.toml`.
fn default_config_path() -> PathBuf {
    config_dir().join("config.toml")
}

/// PID file path: `~/.config/llm-proxy/llm-proxy.pid`.
fn pid_file_path() -> PathBuf {
    config_dir().join("llm-proxy.pid")
}

/// Resolve the config file path for `serve`.
///
/// Priority:
/// 1. Explicit CLI `--config` argument
/// 2. `$LLM_PROXY_CONFIG` env var
/// 3. Default path `~/.config/llm-proxy/config.toml`
fn resolve_serve_config(cli_path: Option<&std::path::Path>) -> PathBuf {
    // 1. Explicit CLI path always wins.
    if let Some(p) = cli_path {
        return p.to_path_buf();
    }
    // 2. Preferred env var.
    if let Ok(p) = std::env::var("LLM_PROXY_CONFIG") {
        if !p.is_empty() {
            return PathBuf::from(p);
        }
    }
    default_config_path()
}

/// Resolve the config file path for non-serve commands (validate, models).
///
/// Priority:
/// 1. Explicit CLI `--config` argument
/// 2. `$LLM_PROXY_CONFIG` env var
/// 3. Default path
fn resolve_config(cli_path: Option<&std::path::Path>) -> PathBuf {
    if let Some(p) = cli_path {
        return p.to_path_buf();
    }
    if let Ok(p) = std::env::var("LLM_PROXY_CONFIG") {
        if !p.is_empty() {
            return PathBuf::from(p);
        }
    }
    default_config_path()
}

/// Returns the providers directory path, which is always `providers/`
/// next to the config file.
///
/// Falls back to `./providers` if the config path has no parent directory
/// (e.g. bare filename `config.toml` with no directory component).
fn providers_dir_for(config_path: &std::path::Path) -> PathBuf {
    config_path
        .parent()
        .unwrap_or(std::path::Path::new("."))
        .join("providers")
}

/// Returns the launchd plist path on macOS.
///
/// Falls back to `./com.llm-proxy.plist` if home directory cannot be determined.
#[cfg(target_os = "macos")]
fn launchd_plist_path() -> PathBuf {
    home_env::home_dir()
        .map(|h| {
            h.join("Library")
                .join("LaunchAgents")
                .join("com.llm-proxy.plist")
        })
        .unwrap_or_else(|| PathBuf::from("com.llm-proxy.plist"))
}

/// Returns the XDG autostart directory on Linux.
///
/// Falls back to `./.config/autostart` if home directory cannot be determined.
#[cfg(target_os = "linux")]
fn linux_autostart_dir() -> PathBuf {
    home_env::home_dir()
        .map(|h| h.join(".config").join("autostart"))
        .unwrap_or_else(|| PathBuf::from(".config/autostart"))
}

// ---------------------------------------------------------------------------
// PID file helpers
// ---------------------------------------------------------------------------

/// Read the PID from the PID file. Returns `None` if the file does not exist.
fn read_pid() -> Result<Option<u32>> {
    let path = pid_file_path();
    if !path.exists() {
        return Ok(None);
    }
    let content = std::fs::read_to_string(&path)
        .with_context(|| format!("reading PID file {}", path.display()))?;
    let pid: u32 = content
        .trim()
        .parse()
        .with_context(|| format!("parsing PID from {}", path.display()))?;
    Ok(Some(pid))
}

/// Atomically create the PID file with exclusive ownership.
///
/// Uses `create_new(true)` so the file is created exclusively -- if another
/// process already created it, the call fails and we return the OS error.
/// This eliminates the TOCTOU race between checking for a stale PID and
/// writing the new one.
fn write_pid() -> Result<()> {
    let dir = config_dir();
    std::fs::create_dir_all(&dir)
        .with_context(|| format!("creating directory {}", dir.display()))?;
    let path = pid_file_path();
    let pid = std::process::id();
    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&path)
        .with_context(|| format!("creating PID file {}", path.display()))?;
    write!(f, "{pid}").with_context(|| format!("writing PID file {}", path.display()))?;
    info!(pid, "wrote PID file");
    Ok(())
}

/// Remove the PID file.
fn remove_pid() -> Result<()> {
    let path = pid_file_path();
    if path.exists() {
        std::fs::remove_file(&path)
            .with_context(|| format!("removing PID file {}", path.display()))?;
    }
    Ok(())
}

/// Check if a process with the given PID is running.
///
/// On Unix, uses `kill(pid, 0)` which checks process existence without
/// sending a signal. Returns `true` when `kill` returns 0 (process exists
/// and we have permission) OR when it returns -1 with `EPERM` (process
/// exists but we lack permission to signal it). Only returns `false` when
/// `ESRCH` is returned (no such process).
fn is_process_running(pid: u32) -> bool {
    // SAFETY: kill(pid, 0) just checks if the process exists; it does not
    // send a signal on any Unix platform. The pid is validated to be a
    // non-zero positive integer by the caller (read from PID file).
    #[cfg(unix)]
    {
        let ret = unsafe { libc::kill(pid as i32, 0) };
        if ret == 0 {
            return true;
        }
        // EPERM means the process exists but we cannot signal it.
        #[cfg(target_os = "macos")]
        let errno = unsafe { *libc::__error() };
        #[cfg(target_os = "linux")]
        let errno = unsafe { *libc::__errno_location() };
        #[cfg(not(any(target_os = "macos", target_os = "linux")))]
        let errno: i32 = 0; // Assume not EPERM on other Unix platforms.
        errno == libc::EPERM
    }
    #[cfg(not(unix))]
    {
        // Fallback: always assume running on non-Unix.
        let _ = pid;
        true
    }
}

// ---------------------------------------------------------------------------
// Config extension validation
// ---------------------------------------------------------------------------

/// Check if a path points to a TOML config file.
fn is_toml_config(path: &std::path::Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| e.eq_ignore_ascii_case("toml"))
}

/// Validate that the config file path has a supported extension.
///
/// Rejects non-TOML paths with an unsupported-extension error.
fn validate_toml_extension(path: &std::path::Path) -> Result<()> {
    if !is_toml_config(path) {
        bail!(
            "unsupported config file extension: {:?} (expected .toml)",
            path.extension()
                .map(|e| e.to_string_lossy())
                .unwrap_or_else(|| std::borrow::Cow::Borrowed("(none)"))
        );
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Serve {
            config,
            port,
            background,
            daemonize,
        } => cmd_serve(config, port, background, daemonize).await,
        Commands::Stop => cmd_stop(),
        Commands::Status => cmd_status(),
        Commands::Init => cmd_init(),
        Commands::Validate { config } => cmd_validate(config),
        Commands::Models {
            config,
            provider,
            live,
            write_catalog,
            require_success,
        } => cmd_models(config, provider, live, write_catalog, require_success).await,
        Commands::Autostart { action } => match action {
            AutostartAction::Enable { config, port } => cmd_autostart_enable(config, port),
            AutostartAction::Disable => cmd_autostart_disable(),
            AutostartAction::Status => cmd_autostart_status(),
        },
    }
}

// ---------------------------------------------------------------------------
// Command implementations
// ---------------------------------------------------------------------------

/// Run the `serve` command.
///
/// Requires TOML configuration.
async fn cmd_serve(
    config_path: Option<PathBuf>,
    port_override: Option<u16>,
    background: bool,
    daemonize: bool,
) -> Result<()> {
    // If background mode requested, spawn self as child with --daemonize.
    if background && !daemonize {
        return spawn_daemon(config_path, port_override);
    }

    init_tracing();

    // Resolve config file path.
    let path = resolve_serve_config(config_path.as_deref());

    validate_toml_extension(&path)?;

    // Build shared infrastructure.
    let adapter_registry = ProviderAdapterRegistry::builtin();
    let proxy_client = ProxyClient::new();

    // Attempt atomic PID file creation. If it fails because the file already
    // exists, check whether the existing owner is still alive before removing
    // the stale file and retrying. This closes the TOCTOU window between the
    // stale-check and the write.
    if let Err(first_err) = write_pid() {
        // Atomic create_new failed -- file exists. Check if the owner is stale.
        if let Some(existing_pid) = read_pid()? {
            if is_process_running(existing_pid) {
                bail!(
                    "server already running with PID {} (PID file: {})",
                    existing_pid,
                    pid_file_path().display()
                );
            }
            info!("stale PID file found (PID {}), cleaning up", existing_pid);
        }
        remove_pid()?;
        // Retry -- this time the file is gone so create_new should succeed.
        write_pid().with_context(|| {
            format!(
                "failed to create PID file after removing stale entry: {}",
                first_err
            )
        })?;
    }

    // Ensure PID file is cleaned up on shutdown.
    let pid_path = pid_file_path();
    let cleanup = async move {
        if let Err(e) = std::fs::remove_file(&pid_path) {
            tracing::warn!(error = %e, "failed to remove PID file during shutdown");
        }
    };

    // Load TOML config and build state (consumes adapter_registry and proxy_client).
    let state = load_toml_state(&path, adapter_registry, proxy_client, port_override)?;

    let bind_addr = state.bind_address();
    let app = build_router(state);

    let listener = TcpListener::bind(bind_addr)
        .await
        .with_context(|| format!("binding to {bind_addr}"))?;
    info!(
        addr = %listener.local_addr()?,
        version = env!("CARGO_PKG_VERSION"),
        "llm-proxy listening"
    );

    // Serve with graceful shutdown.
    let result = axum::serve(
        listener,
        app.into_make_service_with_connect_info::<std::net::SocketAddr>(),
    )
    .with_graceful_shutdown(shutdown_signal())
    .await;

    cleanup.await;

    match result {
        Ok(()) => {
            info!("server stopped cleanly");
            Ok(())
        }
        Err(e) => {
            tracing::error!(error = %e, "server error");
            Err(anyhow::anyhow!("server error: {}", e))
        }
    }
}

/// Spawn the current binary as a background daemon.
fn spawn_daemon(config_path: Option<PathBuf>, port_override: Option<u16>) -> Result<()> {
    let exe = std::env::current_exe().with_context(|| "resolving current executable")?;
    let mut cmd = std::process::Command::new(&exe);
    cmd.arg("serve").arg("--daemonize");

    if let Some(ref p) = config_path {
        cmd.arg("--config").arg(p);
    }
    if let Some(p) = port_override {
        cmd.arg("--port").arg(p.to_string());
    }

    // Detach from terminal.
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        cmd.process_group(0);
        // Redirect stdout/stderr to a log file.
        let log_path = config_dir().join("llm-proxy.log");
        let log_file = std::fs::File::options()
            .create(true)
            .append(true)
            .open(&log_path)
            .with_context(|| format!("opening log file {}", log_path.display()))?;
        cmd.stdout(
            log_file
                .try_clone()
                .with_context(|| "cloning log file handle")?,
        );
        cmd.stderr(log_file);
    }

    #[cfg(not(unix))]
    {
        println!(
            "warning: daemon log redirection is not supported on this platform; \
                   output will be lost"
        );
    }

    let mut child = cmd.spawn().with_context(|| "spawning daemon process")?;

    let pid = child.id();
    println!("llm-proxy started in background (PID {pid})");
    println!("  config dir: {}", config_dir().display());
    println!(
        "  log file:   {}",
        config_dir().join("llm-proxy.log").display()
    );

    // Detach from child so we don't wait on it.
    if let Err(e) = child.try_wait() {
        tracing::warn!(error = %e, "failed to check daemon child status");
    }

    Ok(())
}

/// Run the `stop` command.
fn cmd_stop() -> Result<()> {
    #[cfg(not(unix))]
    {
        bail!("error: stop is not supported on this platform");
    }

    match read_pid()? {
        Some(pid) => {
            if !is_process_running(pid) {
                println!("server not running (stale PID {pid})");
                remove_pid()?;
                return Ok(());
            }

            #[cfg(unix)]
            {
                // Send SIGTERM.
                let ret = unsafe { libc::kill(pid as i32, libc::SIGTERM) };
                if ret != 0 {
                    bail!("failed to send SIGTERM to PID {pid}");
                }
            }

            println!("sent SIGTERM to PID {pid}");

            // Wait briefly for process to exit.
            for _ in 0..10 {
                if !is_process_running(pid) {
                    remove_pid()?;
                    println!("server stopped");
                    return Ok(());
                }
                std::thread::sleep(std::time::Duration::from_millis(200));
            }

            // Force kill if still running.
            #[cfg(unix)]
            {
                let ret = unsafe { libc::kill(pid as i32, libc::SIGKILL) };
                if ret != 0 {
                    bail!("failed to send SIGKILL to PID {pid}");
                }
            }
            remove_pid()?;
            println!("server force-stopped (PID {pid})");
            Ok(())
        }
        None => {
            println!("no PID file found -- server not running");
            Ok(())
        }
    }
}

/// Run the `status` command.
fn cmd_status() -> Result<()> {
    match read_pid()? {
        Some(pid) => {
            if is_process_running(pid) {
                println!("server is running (PID {pid})");
                // Try to load actual bind address from config.
                let config_path = default_config_path();
                if config_path.exists() {
                    if let Ok(cfg) = load_app_config(&config_path) {
                        println!("  listen: {}", cfg.server.bind);
                    } else {
                        println!("  listen: (could not parse config)");
                    }
                } else {
                    println!("  listen: (config not found: {})", config_path.display());
                }
                println!("  config: {}", config_path.display());
            } else {
                println!("server not running (stale PID {pid})");
            }
            Ok(())
        }
        None => {
            println!("server not running (no PID file)");
            Ok(())
        }
    }
}

/// Run the `init` command.
///
/// Creates:
/// - `config.toml` in the config directory
/// - `providers/opencode-go.toml` next to the config
/// - `providers/opencode-zen.toml` next to the config
///
/// Does NOT write:
/// - fallback/scenario JSON
/// - sampling/tool/reasoning/cache/stream overrides
fn cmd_init() -> Result<()> {
    let config_path = default_config_path();
    if config_path.exists() {
        bail!("config file already exists at {}", config_path.display());
    }

    let dir = config_dir();
    std::fs::create_dir_all(&dir)
        .with_context(|| format!("creating directory {}", dir.display()))?;

    // Write main config.toml with restrictive permissions (contains env var references).
    let mut f = std::fs::File::create(&config_path)
        .with_context(|| format!("creating {}", config_path.display()))?;
    f.write_all(DEFAULT_CONFIG_TOML.as_bytes())
        .with_context(|| format!("writing {}", config_path.display()))?;
    set_private_permissions(&config_path)?;
    println!("created config at {}", config_path.display());

    // Create providers directory.
    let providers_dir = providers_dir_for(&config_path);
    std::fs::create_dir_all(&providers_dir)
        .with_context(|| format!("creating directory {}", providers_dir.display()))?;

    // Write opencode-go provider with restrictive permissions.
    let go_path = providers_dir.join("opencode-go.toml");
    let mut f = std::fs::File::create(&go_path)
        .with_context(|| format!("creating {}", go_path.display()))?;
    f.write_all(DEFAULT_PROVIDER_OPENCODE_GO.as_bytes())
        .with_context(|| format!("writing {}", go_path.display()))?;
    set_private_permissions(&go_path)?;
    println!("created provider config at {}", go_path.display());

    // Write opencode-zen provider with restrictive permissions.
    let zen_path = providers_dir.join("opencode-zen.toml");
    let mut f = std::fs::File::create(&zen_path)
        .with_context(|| format!("creating {}", zen_path.display()))?;
    f.write_all(DEFAULT_PROVIDER_OPENCODE_ZEN.as_bytes())
        .with_context(|| format!("writing {}", zen_path.display()))?;
    set_private_permissions(&zen_path)?;
    println!("created provider config at {}", zen_path.display());

    println!();
    println!("Next steps:");
    println!("  1. Set API keys via environment variables:");
    println!("     export LLM_PROXY_OPENCODE_GO_KEY=your-go-key");
    println!("     export LLM_PROXY_OPENCODE_ZEN_KEY=your-zen-key");
    println!("  2. Run `llm-proxy validate` to check your config");
    println!("  3. Run `llm-proxy serve` to start the proxy");

    Ok(())
}

/// Run the `validate` command.
///
/// Loads main TOML, loads provider files, validates provider adapter protocols
/// against builtins, and prints provider route table.
fn cmd_validate(config_path: Option<PathBuf>) -> Result<()> {
    let path = resolve_config(config_path.as_deref());

    // Reject JSON config and non-TOML extensions.
    validate_toml_extension(&path)?;

    println!("validating config: {}", path.display());

    let app_config: AppConfig = load_app_config(&path)
        .with_context(|| format!("loading TOML config from {}", path.display()))?;

    // Print settings summary.
    println!();
    println!("=== Server Configuration ===");
    println!("  bind:            {}", app_config.server.bind);
    println!(
        "  request_timeout: {}s",
        app_config.server.request_timeout.as_secs()
    );
    println!("  log_level:       {}", app_config.server.log_level);
    println!("  hot_reload:      {}", app_config.server.hot_reload);
    println!("  rate_limit_rpm:  {}", app_config.server.rate_limit_rpm);
    println!(
        "  trust_forwarded_headers: {}",
        app_config.server.trust_forwarded_headers
    );
    println!(
        "  dedup_window:    {}ms",
        app_config.server.dedup_window.as_millis()
    );
    println!("  server_name:     {}", app_config.server.server_name);

    // Load and validate providers.
    let providers_dir = providers_dir_for(&path);
    let registry = if providers_dir.exists() {
        ProviderRegistry::load_from_dir(&providers_dir)
            .with_context(|| format!("loading providers from {}", providers_dir.display()))?
    } else {
        ProviderRegistry::from_providers(vec![])
            .with_context(|| "building empty provider registry")?
    };

    // Validate provider protocols against builtin adapters.
    let adapter_registry = ProviderAdapterRegistry::builtin();
    let known_protocols = adapter_registry.protocol_names();
    registry
        .validate_protocols(known_protocols)
        .with_context(|| "validating provider protocols")?;

    println!();
    println!("=== Providers ({} loaded) ===", registry.len());
    if registry.is_empty() {
        println!("  (none)");
    } else {
        for provider in registry.iter() {
            let route_count = provider
                .routes
                .chat_completions
                .iter()
                .chain(provider.routes.messages.iter())
                .count();
            println!(
                "  {} ({} adapters, {} routes, {} aliases)",
                provider.name,
                provider.adapters.len(),
                route_count,
                provider.model_aliases.len()
            );
        }
    }

    // Print provider route table: route_kind -> adapter/protocol
    println!();
    println!("=== Provider Routes ===");
    if registry.is_empty() {
        println!("  (no providers loaded)");
    } else {
        let mut route_errors: Vec<String> = Vec::new();
        for provider in registry.iter() {
            println!("{}:", provider.name);
            let has_routes =
                provider.routes.chat_completions.is_some() || provider.routes.messages.is_some();
            if !has_routes {
                println!("  (no routes configured)");
            } else {
                let route_entries: Vec<(&str, &String)> = provider
                    .routes
                    .chat_completions
                    .as_ref()
                    .map(|a| ("chat_completions", a))
                    .into_iter()
                    .chain(provider.routes.messages.as_ref().map(|a| ("messages", a)))
                    .collect();

                for (route_kind, adapter_name) in &route_entries {
                    match provider.adapters.get(*adapter_name) {
                        Some(adapter) => {
                            println!("  {} -> {}/{}", route_kind, adapter_name, adapter.protocol);
                        }
                        None => {
                            let msg = format!(
                                "  {} -> ERROR: unknown adapter \"{}\"",
                                route_kind, adapter_name
                            );
                            println!("{}", msg);
                            route_errors.push(msg);
                        }
                    }
                }
            }
        }

        if !route_errors.is_empty() {
            bail!(
                "config has {} route resolution error(s)",
                route_errors.len()
            );
        }
    }

    let cache_dir = providers_dir.join(".catalog");
    let warnings: Vec<_> = registry
        .iter()
        .filter_map(|provider| catalog_enforcement_warning(provider, &cache_dir))
        .collect();
    if !warnings.is_empty() {
        println!();
        println!("=== Warnings ===");
        for warning in warnings {
            println!("  WARNING: {warning}");
        }
    }

    println!();
    println!("Config is valid!");
    Ok(())
}

/// Run the `models` command.
///
/// Lists provider routes and static, cached, or live model catalogs.
async fn cmd_models(
    config_path: Option<PathBuf>,
    provider_filter: Option<String>,
    live: bool,
    write_catalog: bool,
    require_success: bool,
) -> Result<()> {
    let path = resolve_config(config_path.as_deref());

    // Reject JSON config and non-TOML extensions.
    validate_toml_extension(&path)?;

    // Load providers from the providers/ directory next to the config.
    let providers_dir = providers_dir_for(&path);
    let registry = if providers_dir.exists() {
        ProviderRegistry::load_from_dir(&providers_dir)
            .with_context(|| format!("loading providers from {}", providers_dir.display()))?
    } else {
        ProviderRegistry::from_providers(vec![])
            .with_context(|| "building empty provider registry")?
    };

    if registry.is_empty() {
        println!("No providers configured.");
        println!("Add provider files to {}", providers_dir.display());
        return Ok(());
    }

    let providers: Vec<_> = registry
        .iter()
        .filter(|p| {
            provider_filter
                .as_ref()
                .is_none_or(|filter| p.name == *filter)
        })
        .collect();

    if provider_filter.is_some() && providers.is_empty() {
        let name = provider_filter.as_deref().unwrap_or("?");
        bail!(
            "provider \"{name}\" not found in {}",
            providers_dir.display()
        );
    }

    let cache_dir = providers_dir.join(".catalog");
    let catalogs = ModelCatalogService::new(Some(cache_dir.clone()));
    let discovery = DiscoveryClient::default();

    println!("Provider models (from {}):", providers_dir.display());
    println!();
    for provider in &providers {
        println!("  {}:", provider.name);

        // Show routes.
        let has_routes =
            provider.routes.chat_completions.is_some() || provider.routes.messages.is_some();
        println!("    routes:");
        if let Some(ref adapter) = provider.routes.chat_completions {
            println!("      chat_completions -> {adapter}");
        }
        if let Some(ref adapter) = provider.routes.messages {
            println!("      messages -> {adapter}");
        }
        if !has_routes {
            println!("      (none configured)");
        }

        let catalog_config = provider.catalog.clone().unwrap_or_default();
        let entries = if live {
            if provider.discovery.is_none() {
                bail!(
                    "provider \"{}\" has no discovery configuration for --live",
                    provider.name
                );
            }
            match discovery.discover(provider).await {
                Ok(discovered) => {
                    let entries = merge_catalog(&catalog_config, &discovered);
                    if write_catalog {
                        write_catalog_atomic(
                            &cache_dir,
                            &CatalogFile {
                                catalog: CatalogFileMetadata {
                                    provider: provider.name.clone(),
                                    source: "live".to_owned(),
                                    generated_at: time::OffsetDateTime::now_utc()
                                        .format(&time::format_description::well_known::Rfc3339)
                                        .unwrap_or_else(|_| "1970-01-01T00:00:00Z".to_owned()),
                                    models: discovered,
                                },
                            },
                        )?;
                    }
                    entries
                }
                Err(error) if require_success => return Err(error.into()),
                Err(error) => {
                    eprintln!(
                        "warning: live discovery failed for {}: {error}; using cached/static catalog",
                        provider.name
                    );
                    catalogs.catalog(provider, false).await?
                }
            }
        } else {
            catalogs.catalog(provider, false).await?
        };

        println!("    models:");
        if entries.is_empty() {
            println!("      (none available)");
        } else {
            for entry in entries {
                println!("      {}", entry.id);
            }
        }
    }

    Ok(())
}

/// Run the `autostart enable` command.
fn cmd_autostart_enable(config_path: Option<PathBuf>, port: Option<u16>) -> Result<()> {
    let dir = config_dir();
    std::fs::create_dir_all(&dir)
        .with_context(|| format!("creating directory {}", dir.display()))?;

    let exe = std::env::current_exe().with_context(|| "resolving current executable")?;
    // Build args as strings for plist/desktop entry display. Lossy conversion is
    // acceptable here because these are display-only strings that are XML-escaped
    // by format_plist(). Non-UTF-8 paths are rare and the lossy replacement is
    // sufficient for auto-start purposes.
    let mut args = vec![exe.to_string_lossy().to_string(), "serve".to_string()];

    if let Some(ref p) = config_path {
        args.push("--config".to_string());
        args.push(p.to_string_lossy().to_string());
    }
    if let Some(p) = port {
        args.push("--port".to_string());
        args.push(p.to_string());
    }

    #[cfg(target_os = "macos")]
    {
        let plist_content = format_plist(&args.join(" "));
        let plist_path = launchd_plist_path();

        let plist_dir = plist_path
            .parent()
            .with_context(|| format!("invalid plist path: {}", plist_path.display()))?;
        std::fs::create_dir_all(plist_dir)
            .with_context(|| format!("creating {}", plist_dir.display()))?;

        std::fs::write(&plist_path, plist_content)
            .with_context(|| format!("writing {}", plist_path.display()))?;
        // Set restrictive permissions on the plist file.
        set_private_permissions(&plist_path)?;

        println!("created launchd plist at {}", plist_path.display());
        println!("run: launchctl load {}", plist_path.display());
    }

    #[cfg(target_os = "linux")]
    {
        let desktop_content = format_desktop_entry(&args.join(" "));
        let autostart_dir = linux_autostart_dir();
        std::fs::create_dir_all(&autostart_dir)
            .with_context(|| format!("creating {}", autostart_dir.display()))?;
        let desktop_path = autostart_dir.join("llm-proxy.desktop");
        std::fs::write(&desktop_path, desktop_content)
            .with_context(|| format!("writing {}", desktop_path.display()))?;
        // Set restrictive permissions on the desktop entry.
        set_private_permissions(&desktop_path)?;
        println!("created desktop entry at {}", desktop_path.display());
    }

    #[cfg(not(any(target_os = "macos", target_os = "linux")))]
    {
        println!("auto-start is not supported on this platform");
        println!("add this command to your shell startup script:");
        println!("  {}", args.join(" "));
    }

    Ok(())
}

/// Run the `autostart disable` command.
fn cmd_autostart_disable() -> Result<()> {
    #[cfg(target_os = "macos")]
    {
        let plist_path = launchd_plist_path();

        if plist_path.exists() {
            let _ = std::process::Command::new("launchctl")
                .args(["unload", &plist_path.to_string_lossy()])
                .output();
            std::fs::remove_file(&plist_path)
                .with_context(|| format!("removing {}", plist_path.display()))?;
            println!("removed launchd plist");
        } else {
            println!("no launchd plist found");
        }
    }

    #[cfg(target_os = "linux")]
    {
        let autostart_dir = linux_autostart_dir();
        let desktop_path = autostart_dir.join("llm-proxy.desktop");
        if desktop_path.exists() {
            std::fs::remove_file(&desktop_path)
                .with_context(|| format!("removing {}", desktop_path.display()))?;
            println!("removed desktop entry");
        } else {
            println!("no desktop entry found");
        }
    }

    #[cfg(not(any(target_os = "macos", target_os = "linux")))]
    {
        println!("auto-start is not supported on this platform");
    }

    Ok(())
}

/// Run the `autostart status` command.
fn cmd_autostart_status() -> Result<()> {
    #[cfg(target_os = "macos")]
    {
        let plist_path = launchd_plist_path();

        if plist_path.exists() {
            println!("auto-start is enabled ({})", plist_path.display());
        } else {
            println!("auto-start is disabled (no launchd plist found)");
        }
    }

    #[cfg(target_os = "linux")]
    {
        let autostart_dir = linux_autostart_dir();
        let desktop_path = autostart_dir.join("llm-proxy.desktop");
        if desktop_path.exists() {
            println!("auto-start is enabled ({})", desktop_path.display());
        } else {
            println!("auto-start is disabled (no desktop entry found)");
        }
    }

    #[cfg(not(any(target_os = "macos", target_os = "linux")))]
    {
        println!("auto-start is not supported on this platform");
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Platform-specific helpers
// ---------------------------------------------------------------------------

/// Generate a macOS launchd plist for auto-start.
///
/// The `command` string is XML-escaped to prevent malformed plists when the
/// executable path contains XML special characters (<, >, &, ", ').
#[cfg(target_os = "macos")]
fn format_plist(command: &str) -> String {
    let escaped_command = xml_escape(command);
    let log_path = config_dir().join("llm-proxy.log").display().to_string();
    let escaped_log = xml_escape(&log_path);
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.llm-proxy</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>-c</string>
        <string>{escaped_command}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>{escaped_log}</string>
    <key>StandardErrorPath</key>
    <string>{escaped_log}</string>
</dict>
</plist>
"#
    )
}

/// Generate a Linux XDG desktop entry for auto-start.
///
/// The `command` string is desktop-entry-escaped for the Exec key.
#[cfg(target_os = "linux")]
fn format_desktop_entry(command: &str) -> String {
    // Desktop entry Exec values need minimal escaping per the spec.
    // In practice, the command is built from paths that rarely contain
    // special characters, but we still escape newlines to prevent
    // multi-line injection.
    let escaped = command.replace('\\', "\\\\").replace('\n', "\\n");
    format!(
        r#"[Desktop Entry]
Type=Application
Name=LLM Proxy
Exec={escaped}
X-GNOME-Autostart-enabled=true
Hidden=false
"#
    )
}

/// Escape a string for safe inclusion in XML content.
///
/// Replaces the five predefined XML entities: `<`, `>`, `&`, `"`, `'`.
fn xml_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(ch),
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Load TOML config files and build [`AppState`] in TOML new-runtime mode.
///
/// Loads the main `AppConfig` from `path`, then scans a `providers/` directory
/// next to `path` for provider TOML files. Uses [`ProviderRegistry::load_from_dir`]
/// which handles non-regular-file filtering, deterministic sorted ordering, and
/// duplicate-name detection. Protocol validation is performed separately against
/// the builtin adapter set after loading.
///
/// Takes ownership of `adapter_registry` and `proxy_client` since they are
/// consumed by [`AppState::new`] and not reused after this call.
fn load_toml_state(
    path: &std::path::Path,
    adapter_registry: ProviderAdapterRegistry,
    proxy_client: ProxyClient,
    port_override: Option<u16>,
) -> Result<AppState> {
    let mut app_config: AppConfig = load_app_config(path)
        .with_context(|| format!("loading TOML config from {}", path.display()))?;

    // Apply CLI port override.
    // In-place mutation is safe here: the config is consumed by AppState::new
    // below and is not shared with any other caller.
    if let Some(p) = port_override {
        let mut bind = app_config.server.bind;
        bind.set_port(p);
        app_config.server.bind = bind;
    }

    // Load provider files from providers/ directory next to the main config.
    let providers_dir = providers_dir_for(path);
    let registry = if providers_dir.exists() {
        ProviderRegistry::load_from_dir(&providers_dir)
            .with_context(|| format!("loading providers from {}", providers_dir.display()))?
    } else {
        ProviderRegistry::from_providers(vec![])
            .with_context(|| "building empty provider registry")?
    };

    // Validate all provider protocols against the builtin adapter set.
    let known_protocols = adapter_registry.protocol_names();
    registry
        .validate_protocols(known_protocols)
        .with_context(|| "validating provider protocols")?;

    let cache_dir = providers_dir.join(".catalog");
    for provider in registry.iter() {
        if let Some(warning) = catalog_enforcement_warning(provider, &cache_dir) {
            tracing::warn!(provider = %provider.name, "{warning}");
        }
    }

    info!(
        config = %path.display(),
        providers = registry.len(),
        "loaded TOML config"
    );

    Ok(AppState::new_with_catalog_dir(
        app_config,
        registry,
        adapter_registry,
        proxy_client,
        build_info(),
        Some(cache_dir),
    ))
}

fn catalog_enforcement_warning(provider: &ProviderConfig, cache_dir: &Path) -> Option<String> {
    let catalog = provider.catalog.as_ref()?;
    if !catalog.enforce || !merge_catalog(catalog, &[]).is_empty() {
        return None;
    }

    let cache_path = cache_dir.join(format!("{}.toml", provider.name));
    let cached_models = std::fs::symlink_metadata(&cache_path)
        .ok()
        .filter(|metadata| metadata.file_type().is_file() && !metadata.file_type().is_symlink())
        .and_then(|_| std::fs::read_to_string(&cache_path).ok())
        .and_then(|raw| parse_catalog_file(&raw).ok())
        .filter(|cache| cache.catalog.provider == provider.name)
        .map(|cache| cache.catalog.models)
        .unwrap_or_default();

    if !merge_catalog(catalog, &cached_models).is_empty() {
        return None;
    }

    Some(format!(
        "provider \"{}\" has catalog enforcement enabled but no allowed models; requests will be rejected until static models are configured or live discovery writes a cache",
        provider.name
    ))
}

fn build_info() -> BuildInfo {
    BuildInfo {
        name: env!("CARGO_PKG_NAME"),
        version: env!("CARGO_PKG_VERSION"),
        target: env!("VERGEN_CARGO_TARGET_TRIPLE"),
        git_sha: env!("VERGEN_GIT_SHA"),
    }
}

fn init_tracing() {
    use tracing_subscriber::{EnvFilter, fmt, layer::SubscriberExt, util::SubscriberInitExt};
    // Fallback to "info" level when RUST_LOG is not set. "info" is a known-valid
    // filter string so parse_lossy is safe here (it never panics).
    let filter = EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| EnvFilter::builder().parse_lossy("info"));
    tracing_subscriber::registry()
        .with(filter)
        .with(fmt::layer())
        .init();
}

// ---------------------------------------------------------------------------
// home_env helper (minimal, no external dep)
// ---------------------------------------------------------------------------

/// Minimal home-directory resolution without depending on the `dirs` crate.
///
/// Checks `$HOME` (macOS/Linux) and `$USERPROFILE` (Windows) only.
/// Does not fall back to `getpwuid()` or XDG defaults. This is intentional:
/// the `dirs` crate is avoided to minimize dependency tree, and these two
/// env vars cover all standard configurations.
mod home_env {
    use std::path::PathBuf;

    /// Returns the user's home directory.
    pub(crate) fn home_dir() -> Option<PathBuf> {
        std::env::var("HOME")
            .or_else(|_| std::env::var("USERPROFILE"))
            .ok()
            .map(PathBuf::from)
    }
}

// ---------------------------------------------------------------------------
// File permissions helper
// ---------------------------------------------------------------------------

/// Set owner-only read/write permissions (0600) on a file.
///
/// Used for config and autostart files that reference API keys via
/// environment variables. On non-Unix platforms this is a no-op.
fn set_private_permissions(path: &std::path::Path) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
            .with_context(|| format!("setting permissions on {}", path.display()))?;
    }
    #[cfg(not(unix))]
    {
        let _ = path;
    }
    Ok(())
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use axum::{Router, routing::get};

    use super::*;

    fn provider_config(raw: &str) -> ProviderConfig {
        toml::from_str::<llm_proxy_core::ProviderFile>(raw)
            .unwrap()
            .provider
    }

    #[test]
    fn models_flags_parse_together() {
        let cli = Cli::try_parse_from([
            "llm-proxy",
            "models",
            "--provider",
            "fireworks",
            "--live",
            "--write-catalog",
            "--require-success",
        ])
        .unwrap();
        let Commands::Models {
            provider,
            live,
            write_catalog,
            require_success,
            ..
        } = cli.command
        else {
            panic!("expected models command");
        };
        assert_eq!(provider.as_deref(), Some("fireworks"));
        assert!(live);
        assert!(write_catalog);
        assert!(require_success);
    }

    #[test]
    fn enforcement_warning_respects_discovered_mode() {
        let provider = provider_config(
            r#"[provider]
name = "test-provider"
api_key = "test-key"
auth_style = "bearer"

[provider.catalog]
mode = "discovered"
enforce = true

[[provider.catalog.models]]
id = "static-model"
"#,
        );
        let directory = tempfile::tempdir().unwrap();

        let warning = catalog_enforcement_warning(&provider, directory.path());

        assert!(warning.is_some());
    }

    #[test]
    fn enforcement_warning_accepts_usable_cache() {
        let provider = provider_config(
            r#"[provider]
name = "test-provider"
api_key = "test-key"
auth_style = "bearer"

[provider.catalog]
mode = "discovered"
enforce = true
"#,
        );
        let directory = tempfile::tempdir().unwrap();
        let cache = CatalogFile {
            catalog: CatalogFileMetadata {
                provider: "test-provider".to_owned(),
                source: "live".to_owned(),
                generated_at: "2026-06-10T00:00:00Z".to_owned(),
                models: vec![llm_proxy_core::StaticModelCatalogEntry {
                    id: "cached-model".to_owned(),
                    display_name: None,
                    supports: Vec::new(),
                    context_length: None,
                }],
            },
        };
        std::fs::write(
            directory.path().join("test-provider.toml"),
            toml::to_string(&cache).unwrap(),
        )
        .unwrap();

        let warning = catalog_enforcement_warning(&provider, directory.path());

        assert!(warning.is_none());
    }

    #[tokio::test]
    async fn models_live_writes_discovered_catalog() {
        let app = Router::new().route(
            "/models",
            get(|| async {
                (
                    [("content-type", "application/json")],
                    r#"{"data":[{"id":"discovered-model"}]}"#,
                )
            }),
        );
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        tokio::spawn(async move {
            axum::serve(listener, app).await.unwrap();
        });

        let directory = tempfile::tempdir().unwrap();
        let config = directory.path().join("config.toml");
        std::fs::write(&config, DEFAULT_CONFIG_TOML).unwrap();
        let providers = directory.path().join("providers");
        std::fs::create_dir(&providers).unwrap();
        std::fs::write(
            providers.join("test-provider.toml"),
            format!(
                r#"[provider]
name = "test-provider"
api_key = "test-key"
auth_style = "bearer"

[provider.discovery]
kind = "openai_compatible_models"
endpoint = "http://{address}/models"
"#
            ),
        )
        .unwrap();

        cmd_models(
            Some(config),
            Some("test-provider".to_owned()),
            true,
            true,
            true,
        )
        .await
        .unwrap();

        let raw =
            std::fs::read_to_string(providers.join(".catalog").join("test-provider.toml")).unwrap();
        let catalog: CatalogFile = toml::from_str(&raw).unwrap();
        assert_eq!(catalog.catalog.models[0].id, "discovered-model");
    }

    #[tokio::test]
    async fn models_live_fetches_even_in_static_catalog_mode() {
        let app = Router::new().route(
            "/models",
            get(|| async {
                (
                    [("content-type", "application/json")],
                    r#"{"data":[{"id":"discovered-model"}]}"#,
                )
            }),
        );
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        tokio::spawn(async move {
            axum::serve(listener, app).await.unwrap();
        });

        let directory = tempfile::tempdir().unwrap();
        let config = directory.path().join("config.toml");
        std::fs::write(&config, DEFAULT_CONFIG_TOML).unwrap();
        let providers = directory.path().join("providers");
        std::fs::create_dir(&providers).unwrap();
        std::fs::write(
            providers.join("test-provider.toml"),
            format!(
                r#"[provider]
name = "test-provider"
api_key = "test-key"
auth_style = "bearer"

[provider.discovery]
kind = "openai_compatible_models"
endpoint = "http://{address}/models"

[provider.catalog]
mode = "static"
"#
            ),
        )
        .unwrap();

        cmd_models(
            Some(config),
            Some("test-provider".to_owned()),
            true,
            true,
            true,
        )
        .await
        .unwrap();

        let raw =
            std::fs::read_to_string(providers.join(".catalog").join("test-provider.toml")).unwrap();
        let catalog: CatalogFile = toml::from_str(&raw).unwrap();
        assert_eq!(catalog.catalog.models[0].id, "discovered-model");
    }

    #[tokio::test]
    async fn models_live_requires_discovery_configuration() {
        let directory = tempfile::tempdir().unwrap();
        let config = directory.path().join("config.toml");
        std::fs::write(&config, DEFAULT_CONFIG_TOML).unwrap();
        let providers = directory.path().join("providers");
        std::fs::create_dir(&providers).unwrap();
        std::fs::write(
            providers.join("test-provider.toml"),
            r#"[provider]
name = "test-provider"
api_key = "test-key"
auth_style = "bearer"
"#,
        )
        .unwrap();

        let error = cmd_models(
            Some(config),
            Some("test-provider".to_owned()),
            true,
            false,
            false,
        )
        .await
        .expect_err("--live requires discovery configuration");

        assert!(error.to_string().contains("no discovery configuration"));
    }
}
